/**
 * OpenAPI generator unit tests (port of OpenApiDocsTests.cs, spec 11 §2).
 */

import { describe, expect, it } from "vitest";
import { generateOpenApi, computeETag, GENERATOR_VERSION } from "../../../src/openapi/generator.js";
import { snapshot, table, col } from "../../helpers/schema.js";

const SCHEMA = snapshot("postgresql", [
  table({
    dbName: "products",
    columns: [
      col("id", "Edm.Int32", { isPrimaryKey: true, isAutoGenerated: true, nullable: false }),
      col("name", "Edm.String", { nullable: false }),
      col("price", "Edm.Decimal", { nullable: true }),
      col("active", "Edm.Boolean", { nullable: false }),
      col("notes", "Edm.String", { nullable: true, maxLength: 500 }),
    ],
    primaryKey: ["id"],
    writable: true,
  }),
  table({
    dbName: "orders_view",
    exposedName: "orders_view",
    columns: [
      col("id", "Edm.Int32", { isPrimaryKey: true, nullable: false }),
      col("total", "Edm.Decimal", { nullable: true }),
    ],
    primaryKey: ["id"],
    isView: true,
    writable: false,
  }),
]);

describe("generateOpenApi", () => {
  describe("OData dialect", () => {
    it("produces valid JSON", () => {
      const doc = generateOpenApi(SCHEMA, "odata", "test", "Test Service", "v1", "http://localhost/odata/test");
      expect(() => JSON.parse(doc)).not.toThrow();
    });

    it("contains openapi 3.1.0", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "Test", "v1", "http://localhost"));
      expect(doc.openapi).toBe("3.1.0");
    });

    it("contains OData in the title", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "My API", "v1", "http://localhost"));
      expect(doc.info.title).toContain("OData");
    });

    it("includes schema version in info", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "My API", "v42", "http://localhost"));
      expect(doc.info["x-ez-schema-version"]).toBe("v42");
    });

    it("generates paths for OData collection and by-key", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.paths["/products"]).toBeDefined();
      expect(doc.paths["/products({id})"]).toBeDefined();
    });

    it("generates POST on collection for writable tables", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.paths["/products"]["post"]).toBeDefined();
    });

    it("does not generate POST for views (non-writable)", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.paths["/orders_view"]["post"]).toBeUndefined();
    });

    it("generates PATCH and DELETE on keyed paths for writable", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.paths["/products({id})"]["patch"]).toBeDefined();
      expect(doc.paths["/products({id})"]["delete"]).toBeDefined();
    });

    it("generates read/create/update schemas per table", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.components.schemas["products"]).toBeDefined();
      expect(doc.components.schemas["productsCreate"]).toBeDefined();
      expect(doc.components.schemas["productsUpdate"]).toBeDefined();
    });

    it("excludes auto-generated columns from write schemas", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      const createSchema = doc.components.schemas["productsCreate"];
      expect(createSchema.properties["id"]).toBeUndefined();
      expect(createSchema.properties["name"]).toBeDefined();
    });

    it("maps Edm.Int32 to integer/int32", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      const idProp = doc.components.schemas["products"].properties["id"];
      expect(idProp.type).toBe("integer");
      expect(idProp.format).toBe("int32");
    });

    it("maps Edm.Decimal to string with x-ez-decimal annotation", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      const priceProp = doc.components.schemas["products"].properties["price"];
      expect(priceProp.type).toBe("string");
      expect(priceProp["x-ez-decimal"]).toBe(true);
    });

    it("includes maxLength constraint on string columns", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      const notesProp = doc.components.schemas["products"].properties["notes"];
      expect(notesProp.maxLength).toBe(500);
    });

    it("marks nullable columns", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      const priceProp = doc.components.schemas["products"].properties["price"];
      expect(priceProp.nullable).toBe(true);
    });

    it("security schemes include apiKey and bearer", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.components.securitySchemes["apiKey"]).toBeDefined();
      expect(doc.components.securitySchemes["bearer"]).toBeDefined();
    });
  });

  describe("REST dialect", () => {
    it("contains REST in the title", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "rest", "test", "My API", "v1", "http://localhost"));
      expect(doc.info.title).toContain("REST");
    });

    it("generates /_table/{name} paths", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "rest", "test", "T", "v1", "http://localhost"));
      expect(doc.paths["/_table/products"]).toBeDefined();
      expect(doc.paths["/_table/products/{id}"]).toBeDefined();
    });

    it("REST list parameters use filter/limit/offset", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "rest", "test", "T", "v1", "http://localhost"));
      const params = doc.paths["/_table/products"]["get"]["parameters"] as { name: string }[];
      const names = params.map((p) => p.name);
      expect(names).toContain("filter");
      expect(names).toContain("limit");
      expect(names).toContain("offset");
      expect(names).not.toContain("$filter");
    });
  });

  describe("computeETag", () => {
    it("returns a W/ ETag string", () => {
      const etag = computeETag("v1", "r1", "odata");
      expect(etag).toMatch(/^W\/"[0-9a-f]+"/);
    });

    it("is deterministic", () => {
      expect(computeETag("v1", "r1", "odata")).toBe(computeETag("v1", "r1", "odata"));
    });

    it("differs for different inputs", () => {
      expect(computeETag("v1", "r1", "odata")).not.toBe(computeETag("v2", "r1", "odata"));
    });
  });

  describe("generator version", () => {
    it("is present", () => {
      expect(GENERATOR_VERSION).toBeTruthy();
    });

    it("is included in generated doc", () => {
      const doc = JSON.parse(generateOpenApi(SCHEMA, "odata", "test", "T", "v1", "http://localhost"));
      expect(doc.info["x-ez-generator-version"]).toBe(GENERATOR_VERSION);
    });
  });
});
