using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Testcontainers.MySql;
using Xunit;

namespace EzOdata.IntegrationTests;

/// <summary>
/// MySQL engine end-to-end (spec 14 M4): introspection (incl. enum + auto_increment),
/// reads/filters/navigation, and the LAST_INSERT_ID write-back path (no RETURNING).
/// </summary>
public class MySqlEndToEndTests : IClassFixture<HostFixture>, IAsyncLifetime
{
    private readonly HostFixture _fixture;
    private readonly MySqlContainer _mysql = new MySqlBuilder()
        .WithImage("mysql:8.0")
        .WithDatabase("shop")
        .WithUsername("ez")
        .WithPassword("ez-test-password")
        .Build();

    private HttpClient _client = null!;

    public MySqlEndToEndTests(HostFixture fixture) => _fixture = fixture;

    public async Task InitializeAsync()
    {
        await _mysql.StartAsync();

        const string sql = """
            CREATE TABLE brands (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL
            );
            CREATE TABLE items (
                id INT AUTO_INCREMENT PRIMARY KEY,
                brand_id INT NOT NULL,
                name VARCHAR(200) NOT NULL,
                status ENUM('draft','active','retired') NOT NULL DEFAULT 'draft',
                price DECIMAL(10,2) NOT NULL,
                CONSTRAINT fk_items_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
            );
            INSERT INTO brands (name) VALUES ('Acme'), ('Globex');
            INSERT INTO items (brand_id, name, status, price) VALUES
                (1, 'Anvil', 'active', 29.99),
                (1, 'Rocket', 'active', 199.00),
                (2, 'Widget', 'draft', 4.50);
            """;
        var exec = await _mysql.ExecScriptAsync(sql);
        if (exec.ExitCode != 0) throw new InvalidOperationException("MySQL fixture failed: " + exec.Stderr);

        _client = await _fixture.CreateAdminClientAsync();
        var create = await _client.PostAsJsonAsync("/system/services", new
        {
            name = "shop",
            label = "Shop (MySQL)",
            connectorType = "mysql",
            connection = new
            {
                host = _mysql.Hostname,
                port = _mysql.GetMappedPublicPort(3306),
                database = "shop",
                username = "ez",
                password = "ez-test-password",
                tls = new { mode = "disable" },
            },
        });
        create.EnsureSuccessStatusCode();
        var serviceId = (await create.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetInt64();

        var deadline = DateTime.UtcNow.AddSeconds(40);
        while (DateTime.UtcNow < deadline)
        {
            var service = await _client.GetFromJsonAsync<JsonElement>($"/system/services/{serviceId}");
            var status = service.GetProperty("status").GetString();
            if (status == "Active") return;
            if (status == "Failed") throw new InvalidOperationException("MySQL introspection failed: " + service.GetProperty("statusDetail"));
            await Task.Delay(400);
        }

        throw new TimeoutException("MySQL service did not become Active.");
    }

    async Task IAsyncLifetime.DisposeAsync() => await _mysql.DisposeAsync();

    [Fact]
    public async Task MySql_full_lifecycle()
    {
        await Introspection_maps_enum_and_autoincrement();
        await Reads_filters_navigation_and_writes();
    }

    private async Task Introspection_maps_enum_and_autoincrement()
    {
        var schema = await _client.GetFromJsonAsync<JsonElement>("/system/services/1/schema");
        var items = schema.GetProperty("tables").EnumerateArray()
            .First(t => t.GetProperty("exposedName").GetString() == "items");

        var status = items.GetProperty("columns").EnumerateArray()
            .First(c => c.GetProperty("exposedName").GetString() == "status");
        Assert.Equal("Edm.String", status.GetProperty("edmType").GetString());
        Assert.Equal(["draft", "active", "retired"],
            status.GetProperty("allowedValues").EnumerateArray().Select(v => v.GetString()!).ToArray());

        var id = items.GetProperty("columns").EnumerateArray()
            .First(c => c.GetProperty("exposedName").GetString() == "id");
        Assert.True(id.GetProperty("isAutoGenerated").GetBoolean());
    }

    private async Task Reads_filters_navigation_and_writes()
    {
        // Filter + order
        var items = await _client.GetFromJsonAsync<JsonElement>(
            "/api/odata/shop/items?$filter=price gt 10 and status eq 'active'&$orderby=price desc&$count=true");
        Assert.Equal(2, items.GetProperty("@odata.count").GetInt64());
        Assert.Equal("Rocket", items.GetProperty("value")[0].GetProperty("name").GetString());

        // Navigation filter
        var acme = await _client.GetFromJsonAsync<JsonElement>(
            "/api/odata/shop/items/$count?$filter=brand/name eq 'Acme'");
        Assert.Equal(2, acme.GetInt32());

        // Insert (LAST_INSERT_ID write-back, no RETURNING) returns the generated key
        var create = await _client.PostAsJsonAsync("/api/odata/shop/brands", new { name = "Initech" });
        var createBody = await create.Content.ReadAsStringAsync();
        Assert.True(create.StatusCode == HttpStatusCode.Created, $"Create body: {createBody}");
        var brand = JsonSerializer.Deserialize<JsonElement>(createBody);
        Assert.True(brand.TryGetProperty("id", out _), $"Insert representation missing id. Body: {createBody}");
        var brandId = brand.GetProperty("id").GetInt32();
        Assert.True(brandId > 2);
        Assert.Equal("Initech", brand.GetProperty("name").GetString());

        // Enum constraint enforced on write
        var badEnum = await _client.PostAsJsonAsync("/api/odata/shop/items",
            new { brand_id = brandId, name = "X", status = "bogus", price = 1.0 });
        Assert.Equal(HttpStatusCode.BadRequest, badEnum.StatusCode);

        // FK violation taxonomy
        var badFk = await _client.PostAsJsonAsync("/api/odata/shop/items",
            new { brand_id = 9999, name = "Orphan", price = 1.0 });
        Assert.Equal(HttpStatusCode.Conflict, badFk.StatusCode);
        Assert.Contains("Conflict.ForeignKeyViolation", await badFk.Content.ReadAsStringAsync());

        // Update + delete
        var patch = await _client.PatchAsJsonAsync($"/api/odata/shop/brands({brandId})", new { name = "Initech Inc" });
        Assert.Equal(HttpStatusCode.OK, patch.StatusCode);
        Assert.Equal("Initech Inc", (await patch.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("name").GetString());

        Assert.Equal(HttpStatusCode.NoContent, (await _client.DeleteAsync($"/api/odata/shop/brands({brandId})")).StatusCode);
    }
}
