using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Testcontainers.MsSql;
using Xunit;

namespace EzOdata.IntegrationTests;

/// <summary>
/// SQL Server engine end-to-end (spec 14 M4): introspection (IDENTITY columns, FKs),
/// reads/filters/navigation, and the OUTPUT-clause write-back path (SQL Server has no
/// RETURNING). Uses Testcontainers mssql/server; on arm64 it runs under emulation.
/// </summary>
public class SqlServerEndToEndTests : IClassFixture<HostFixture>, IAsyncLifetime
{
    private readonly HostFixture _fixture;
    private readonly MsSqlContainer _mssql = new MsSqlBuilder()
        .WithImage("mcr.microsoft.com/mssql/server:2022-latest")
        .Build();

    private HttpClient _client = null!;

    public SqlServerEndToEndTests(HostFixture fixture) => _fixture = fixture;

    public async Task InitializeAsync()
    {
        await _mssql.StartAsync();

        // SQL Server images don't create a user database on startup, so make one.
        var create = await _mssql.ExecScriptAsync("CREATE DATABASE shop;");
        if (create.ExitCode != 0) throw new InvalidOperationException("CREATE DATABASE failed: " + create.Stderr);

        const string schema = """
            USE shop;
            CREATE TABLE brands (
                id INT IDENTITY(1,1) PRIMARY KEY,
                name NVARCHAR(100) NOT NULL
            );
            CREATE TABLE items (
                id INT IDENTITY(1,1) PRIMARY KEY,
                brand_id INT NOT NULL,
                name NVARCHAR(200) NOT NULL,
                status NVARCHAR(20) NOT NULL CONSTRAINT df_items_status DEFAULT 'draft',
                price DECIMAL(10,2) NOT NULL,
                CONSTRAINT fk_items_brand FOREIGN KEY (brand_id) REFERENCES brands(id)
            );
            INSERT INTO brands (name) VALUES ('Acme'), ('Globex');
            INSERT INTO items (brand_id, name, status, price) VALUES
                (1, 'Anvil', 'active', 29.99),
                (1, 'Rocket', 'active', 199.00),
                (2, 'Widget', 'draft', 4.50);
            """;
        var seed = await _mssql.ExecScriptAsync(schema);
        if (seed.ExitCode != 0) throw new InvalidOperationException("Schema seed failed: " + seed.Stderr);

        // Pull host/port/password from the container's connection string.
        var csb = new SqlConnectionStringBuilder(_mssql.GetConnectionString());

        _client = await _fixture.CreateAdminClientAsync();
        var createService = await _client.PostAsJsonAsync("/system/services", new
        {
            name = "shop",
            label = "Shop (SQL Server)",
            connectorType = "sqlserver",
            connection = new
            {
                host = _mssql.Hostname,
                port = _mssql.GetMappedPublicPort(1433),
                database = "shop",
                username = csb.UserID,
                password = csb.Password,
                tls = new { mode = "require", allowInvalid = true }, // container uses a self-signed cert
            },
        });
        createService.EnsureSuccessStatusCode();
        var serviceId = (await createService.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetInt64();

        var deadline = DateTime.UtcNow.AddSeconds(60);
        while (DateTime.UtcNow < deadline)
        {
            var service = await _client.GetFromJsonAsync<JsonElement>($"/system/services/{serviceId}");
            var status = service.GetProperty("status").GetString();
            if (status == "Active") return;
            if (status == "Failed") throw new InvalidOperationException("SQL Server introspection failed: " + service.GetProperty("statusDetail"));
            await Task.Delay(500);
        }

        throw new TimeoutException("SQL Server service did not become Active.");
    }

    async Task IAsyncLifetime.DisposeAsync() => await _mssql.DisposeAsync();

    [Fact]
    public async Task SqlServer_full_lifecycle()
    {
        await IntrospectionMapsIdentityAndFk();
        await ReadsFiltersNavigationAndWrites();
    }

    private async Task IntrospectionMapsIdentityAndFk()
    {
        var schema = await _client.GetFromJsonAsync<JsonElement>("/system/services/1/schema");
        var tables = schema.GetProperty("tables").EnumerateArray().ToList();

        var items = tables.First(t => t.GetProperty("exposedName").GetString() == "items");
        var id = items.GetProperty("columns").EnumerateArray().First(c => c.GetProperty("exposedName").GetString() == "id");
        Assert.True(id.GetProperty("isAutoGenerated").GetBoolean());       // IDENTITY → auto-generated
        Assert.True(id.GetProperty("isPrimaryKey").GetBoolean());

        var price = items.GetProperty("columns").EnumerateArray().First(c => c.GetProperty("exposedName").GetString() == "price");
        Assert.Equal("Edm.Decimal", price.GetProperty("edmType").GetString());

        // FK navigation discovered (items.brand_id → brands)
        var fk = items.GetProperty("foreignKeys").EnumerateArray().Single();
        Assert.Equal("brands", fk.GetProperty("refTable").GetString());
        Assert.Equal("brand", fk.GetProperty("navToOne").GetString());
    }

    private async Task ReadsFiltersNavigationAndWrites()
    {
        // Filter + order (OFFSET/FETCH pagination requires the ORDER BY the compiler always emits)
        var items = await _client.GetFromJsonAsync<JsonElement>(
            "/api/odata/shop/items?$filter=price gt 10 and status eq 'active'&$orderby=price desc&$count=true");
        Assert.Equal(2, items.GetProperty("@odata.count").GetInt64());
        Assert.Equal("Rocket", items.GetProperty("value")[0].GetProperty("name").GetString());

        // To-one navigation filter
        var acme = await _client.GetFromJsonAsync<JsonElement>(
            "/api/odata/shop/items/$count?$filter=brand/name eq 'Acme'");
        Assert.Equal(2, acme.GetInt32());

        // $expand to-many
        var withItems = await _client.GetFromJsonAsync<JsonElement>(
            "/api/odata/shop/brands(1)?$expand=items");
        Assert.Equal("Acme", withItems.GetProperty("name").GetString());
        Assert.Equal(2, withItems.GetProperty("items").GetArrayLength());

        // Insert via OUTPUT INSERTED.* returns the IDENTITY key
        var create = await _client.PostAsJsonAsync("/api/odata/shop/brands", new { name = "Initech" });
        Assert.Equal(HttpStatusCode.Created, create.StatusCode);
        var brand = await create.Content.ReadFromJsonAsync<JsonElement>();
        var brandId = brand.GetProperty("id").GetInt32();
        Assert.True(brandId > 2);
        Assert.Equal("Initech", brand.GetProperty("name").GetString());

        // FK violation → 409 via the error taxonomy
        var badFk = await _client.PostAsJsonAsync("/api/odata/shop/items",
            new { brand_id = 9999, name = "Orphan", price = 1.0 });
        Assert.Equal(HttpStatusCode.Conflict, badFk.StatusCode);
        Assert.Contains("Conflict.ForeignKeyViolation", await badFk.Content.ReadAsStringAsync());

        // Update + delete
        var patch = await _client.PatchAsJsonAsync($"/api/odata/shop/brands({brandId})", new { name = "Initech Inc" });
        Assert.Equal(HttpStatusCode.OK, patch.StatusCode);
        Assert.Equal("Initech Inc", (await patch.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("name").GetString());

        Assert.Equal(HttpStatusCode.NoContent, (await _client.DeleteAsync($"/api/odata/shop/brands({brandId})")).StatusCode);
    }
}
