import { ErrorCodes } from "../../core/errors.js";
import {
  isNavigated,
  leaf,
  type Aggregation,
  type ComparisonNode,
  type ComparisonOp,
  type FieldRef,
  type FilterNode,
  type FunctionNode,
  type InNode,
  type LambdaNode,
  type OrderByItem,
  type QueryRequest,
} from "../../core/query.js";
import { findColumn, findTable, hasKey, type ColumnModel, type ForeignKeyModel, type SchemaSnapshot, type TableModel } from "../../core/schema.js";
import { NotSupportedQueryError, QueryValidationError, type SqlDialect } from "../contracts.js";

export interface SqlParam {
  readonly name: string;
  readonly value: unknown;
}

export interface CompiledQuery {
  readonly sql: string;
  readonly parameters: readonly SqlParam[];
  readonly projection: readonly ColumnModel[];
}

/**
 * Compiles Query IR to parameterized SQL (port of SqlCompiler.cs, spec 04 §7).
 * Structure and parameterization are shared; syntax differences go through
 * {@link SqlDialect}.
 *
 * Safety invariants (NFR-3, CON-3):
 * - every identifier is resolved against the schema snapshot, then dialect-quoted;
 *   client strings never reach SQL text directly
 * - every value becomes a parameter; no code path renders a constant inline
 */
export class SqlCompiler {
  constructor(private readonly dialect: SqlDialect) {}

  compileSelect(schema: SchemaSnapshot, query: QueryRequest): CompiledQuery {
    const ctx = new CompileContext(schema, this.dialect, resolveTable(schema, query.table));

    const projection = resolveProjection(ctx.rootTable, query.select);
    const selectList = projection
      .map((c) => `t0.${this.dialect.quoteIdentifier(c.dbName)} AS ${this.dialect.quoteIdentifier(c.exposedName)}`)
      .join(", ");

    const where = query.filter === undefined ? undefined : this.renderFilter(ctx, query.filter, "t0", ctx.rootTable);
    const orderBy = this.renderOrderBy(ctx, query.orderBy, projection);

    let sql = `SELECT ${selectList} FROM ${this.qualifiedTable(ctx.rootTable)} AS t0`;
    for (const join of ctx.joins) sql += ` ${join}`;
    if (where !== undefined) sql += ` WHERE ${where}`;
    if (orderBy.length > 0) sql += ` ORDER BY ${orderBy}`;

    // Fetch one extra row to detect hasMore without a second query.
    const paged = this.dialect.paginate(sql, query.top !== undefined ? query.top + 1 : undefined, query.skip);
    return { sql: paged, parameters: ctx.parameters, projection };
  }

  compileApply(schema: SchemaSnapshot, query: QueryRequest): CompiledQuery {
    const apply = query.apply;
    if (apply === undefined) {
      throw new QueryValidationError(ErrorCodes.ValidationInvalidValue, "No $apply clause to compile.");
    }
    const ctx = new CompileContext(schema, this.dialect, resolveTable(schema, query.table));
    const table = ctx.rootTable;

    const projection: string[] = [];
    const resultColumns: ColumnModel[] = [];

    for (const groupField of apply.groupBy) {
      const column = findColumn(table, groupField);
      if (column === undefined) {
        throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown groupby property '${groupField}'.`);
      }
      projection.push(`t0.${this.dialect.quoteIdentifier(column.dbName)} AS ${this.dialect.quoteIdentifier(column.exposedName)}`);
      resultColumns.push(column);
    }

    for (const aggregate of apply.aggregations) {
      projection.push(`${this.renderAggregate(table, aggregate)} AS ${this.dialect.quoteIdentifier(aggregate.alias)}`);
      resultColumns.push({
        dbName: aggregate.alias,
        exposedName: aggregate.alias,
        dbType: "aggregate",
        edmType: aggregate.op === "count" || aggregate.op === "countDistinct" ? "Edm.Int64" : "Edm.Decimal",
        nullable: true,
        isPrimaryKey: false,
        isAutoGenerated: false,
        isComputed: false,
        isFallbackType: false,
      });
    }

    const where = query.filter === undefined ? undefined : this.renderFilter(ctx, query.filter, "t0", table);

    let sql = `SELECT ${projection.join(", ")} FROM ${this.qualifiedTable(table)} AS t0`;
    for (const join of ctx.joins) sql += ` ${join}`;
    if (where !== undefined) sql += ` WHERE ${where}`;

    if (apply.groupBy.length > 0) {
      const groupCols = apply.groupBy.map((g) => `t0.${this.dialect.quoteIdentifier(findColumn(table, g)!.dbName)}`);
      sql += ` GROUP BY ${groupCols.join(", ")}`;
    }

    return { sql, parameters: ctx.parameters, projection: resultColumns };
  }

  compileCount(schema: SchemaSnapshot, query: QueryRequest): CompiledQuery {
    const ctx = new CompileContext(schema, this.dialect, resolveTable(schema, query.table));
    const where = query.filter === undefined ? undefined : this.renderFilter(ctx, query.filter, "t0", ctx.rootTable);

    let sql = `SELECT COUNT(*) FROM ${this.qualifiedTable(ctx.rootTable)} AS t0`;
    for (const join of ctx.joins) sql += ` ${join}`;
    if (where !== undefined) sql += ` WHERE ${where}`;

    return { sql, parameters: ctx.parameters, projection: [] };
  }

  private renderAggregate(table: TableModel, aggregate: Aggregation): string {
    if (aggregate.op === "count") {
      return "COUNT(*)";
    }
    const column = findColumn(table, aggregate.field ?? "");
    if (column === undefined) {
      throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown aggregate property '${aggregate.field}'.`);
    }
    const quoted = `t0.${this.dialect.quoteIdentifier(column.dbName)}`;
    switch (aggregate.op) {
      case "sum":
        return `SUM(${quoted})`;
      case "average":
        return `AVG(${quoted})`;
      case "min":
        return `MIN(${quoted})`;
      case "max":
        return `MAX(${quoted})`;
      case "countDistinct":
        return `COUNT(DISTINCT ${quoted})`;
      default:
        throw new NotSupportedQueryError(`Unsupported aggregate ${aggregate.op}.`);
    }
  }

  private qualifiedTable(table: TableModel): string {
    return table.dbSchema === ""
      ? this.dialect.quoteIdentifier(table.dbName)
      : `${this.dialect.quoteIdentifier(table.dbSchema)}.${this.dialect.quoteIdentifier(table.dbName)}`;
  }

  private renderOrderBy(ctx: CompileContext, orderBy: readonly OrderByItem[], projection: readonly ColumnModel[]): string {
    const parts: string[] = [];
    const seen = new Set<string>();

    for (const item of orderBy) {
      const column = findColumn(ctx.rootTable, item.field);
      if (column === undefined) {
        throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown property '${item.field}' in $orderby.`);
      }
      parts.push(`t0.${this.dialect.quoteIdentifier(column.dbName)}${item.descending ? " DESC" : ""}`);
      seen.add(column.exposedName);
    }

    // Deterministic pagination (OD-12): PK appended as tiebreaker; keyless tables
    // fall back to all projected columns.
    const tiebreakers = hasKey(ctx.rootTable) ? ctx.rootTable.primaryKey : projection.map((c) => c.exposedName);
    for (const key of tiebreakers) {
      if (seen.has(key)) continue;
      const column = findColumn(ctx.rootTable, key);
      if (column !== undefined) parts.push(`t0.${this.dialect.quoteIdentifier(column.dbName)}`);
    }

    return parts.join(", ");
  }

  private renderFilter(ctx: CompileContext, node: FilterNode, alias: string, table: TableModel): string {
    switch (node.kind) {
      case "logical":
        return (
          "(" +
          node.operands.map((o) => this.renderFilter(ctx, o, alias, table)).join(node.op === "and" ? " AND " : " OR ") +
          ")"
        );
      case "not":
        return `NOT (${this.renderFilter(ctx, node.operand, alias, table)})`;
      case "comparison":
        return this.renderComparison(ctx, node, alias, table);
      case "in":
        return this.renderIn(ctx, node, alias, table);
      case "function":
        return this.renderFunction(ctx, node, alias, table);
      case "lambda":
        return this.renderLambda(ctx, node, alias, table);
      default:
        throw new NotSupportedQueryError(`Unsupported filter construct '${(node as { kind: string }).kind}'.`);
    }
  }

  private renderComparison(ctx: CompileContext, cmp: ComparisonNode, alias: string, table: TableModel): string {
    const { sql: fieldSql } = this.resolveFieldRef(ctx, cmp.field, alias, table);

    if (cmp.value.value === null) {
      switch (cmp.op) {
        case "eq":
          return `${fieldSql} IS NULL`;
        case "ne":
          return `${fieldSql} IS NOT NULL`;
        default:
          throw new QueryValidationError(ErrorCodes.ValidationBadFilter, "null can only be compared with eq/ne.");
      }
    }

    return `${fieldSql} ${opSql(cmp.op)} ${ctx.addParameter(cmp.value.value)}`;
  }

  private renderIn(ctx: CompileContext, node: InNode, alias: string, table: TableModel): string {
    if (node.values.length === 0) {
      return "1 = 0"; // empty IN list matches nothing, by definition
    }
    const { sql: fieldSql } = this.resolveFieldRef(ctx, node.field, alias, table);
    const markers = node.values.map((v) => {
      if (v.value === null) {
        throw new QueryValidationError(ErrorCodes.ValidationBadFilter, "null is not allowed in 'in' lists.");
      }
      return ctx.addParameter(v.value);
    });
    return `${fieldSql} IN (${markers.join(", ")})`;
  }

  private renderFunction(ctx: CompileContext, node: FunctionNode, alias: string, table: TableModel): string {
    const args: string[] = [];
    for (const arg of node.args) {
      if (arg.kind === "field") {
        args.push(this.resolveFieldRef(ctx, arg.field, alias, table).sql);
      } else {
        let value = arg.value.value;
        if (
          (node.fn === "contains" || node.fn === "startsWith" || node.fn === "endsWith") &&
          typeof value === "string"
        ) {
          const escaped = escapeLike(value);
          value = node.fn === "contains" ? `%${escaped}%` : node.fn === "startsWith" ? `${escaped}%` : `%${escaped}`;
        }
        args.push(ctx.addParameter(value));
      }
    }

    const rendered = this.dialect.mapFunction(node.fn, args);

    if (node.op !== undefined && node.comparand !== undefined) {
      if (node.comparand.value === null) {
        switch (node.op) {
          case "eq":
            return `${rendered} IS NULL`;
          case "ne":
            return `${rendered} IS NOT NULL`;
          default:
            throw new QueryValidationError(ErrorCodes.ValidationBadFilter, "null can only be compared with eq/ne.");
        }
      }
      return `${rendered} ${opSql(node.op)} ${ctx.addParameter(node.comparand.value)}`;
    }

    return rendered;
  }

  private renderLambda(ctx: CompileContext, node: LambdaNode, alias: string, table: TableModel): string {
    // any/all over a to-many navigation -> EXISTS subquery (spec 04 §7.2)
    const nav = findToManyNavigation(ctx.schema, table, node.navigation);
    if (nav === undefined) {
      throw new QueryValidationError(
        ErrorCodes.ValidationBadFilter,
        `Unknown collection navigation '${node.navigation}' on '${table.exposedName}'.`,
      );
    }
    const { child: childTable, fk } = nav;
    const childAlias = ctx.nextLambdaAlias();

    const joinCondition = fk.columns
      .map((col, i) => {
        const childColumn = findColumn(childTable, col) ?? childTable.columns.find((c) => c.dbName === col)!;
        const refCol = fk.refColumns[i]!;
        const parentColumn = table.columns.find((c) => c.exposedName === refCol || c.dbName === refCol)!;
        return `${childAlias}.${this.dialect.quoteIdentifier(childColumn.dbName)} = ${alias}.${this.dialect.quoteIdentifier(parentColumn.dbName)}`;
      })
      .join(" AND ");

    const predicate = node.predicate === undefined ? undefined : this.renderFilter(ctx, node.predicate, childAlias, childTable);
    const subquery = `SELECT 1 FROM ${this.qualifiedTable(childTable)} AS ${childAlias} WHERE ${joinCondition}`;

    if (node.lambdaKind === "any") {
      return predicate === undefined ? `EXISTS (${subquery})` : `EXISTS (${subquery} AND ${predicate})`;
    }
    // all(p) === NOT EXISTS (child WHERE NOT p)
    if (predicate === undefined) {
      throw new QueryValidationError(ErrorCodes.ValidationBadFilter, "all() requires a predicate.");
    }
    return `NOT EXISTS (${subquery} AND NOT (${predicate}))`;
  }

  private resolveFieldRef(
    ctx: CompileContext,
    field: FieldRef,
    alias: string,
    table: TableModel,
  ): { sql: string; column: ColumnModel } {
    if (!isNavigated(field)) {
      const column = findColumn(table, leaf(field));
      if (column === undefined) {
        throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown property '${leaf(field)}' on '${table.exposedName}'.`);
      }
      return { sql: `${alias}.${this.dialect.quoteIdentifier(column.dbName)}`, column };
    }

    // To-one navigation path, depth <= 2 (spec 05 §4.3): customer/country
    if (field.path.length > 3) {
      throw new NotSupportedQueryError("Navigation paths in filters are limited to depth 2.");
    }

    let currentTable = table;
    let currentAlias = alias;
    for (let i = 0; i < field.path.length - 1; i++) {
      const navName = field.path[i]!;
      const fk = currentTable.foreignKeys.find((f) => f.navToOne === navName);
      if (fk === undefined) {
        throw new QueryValidationError(ErrorCodes.ValidationBadFilter, `Unknown navigation '${navName}' on '${currentTable.exposedName}'.`);
      }
      const target = findTable(ctx.schema, fk.refTable);
      if (target === undefined) {
        throw new QueryValidationError(ErrorCodes.ValidationInvalidValue, `Navigation '${navName}' references unknown table '${fk.refTable}'.`);
      }
      currentAlias = ctx.ensureJoin(currentAlias, currentTable, fk, target, this.qualifiedTable(target));
      currentTable = target;
    }

    const leafColumn = findColumn(currentTable, leaf(field));
    if (leafColumn === undefined) {
      throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown property '${leaf(field)}' on '${currentTable.exposedName}'.`);
    }
    return { sql: `${currentAlias}.${this.dialect.quoteIdentifier(leafColumn.dbName)}`, column: leafColumn };
  }
}

function resolveTable(schema: SchemaSnapshot, exposedName: string): TableModel {
  const table = findTable(schema, exposedName);
  if (table === undefined) {
    throw new QueryValidationError(ErrorCodes.ValidationInvalidValue, `Unknown table '${exposedName}'.`);
  }
  return table;
}

function resolveProjection(table: TableModel, select: readonly string[] | undefined): readonly ColumnModel[] {
  if (select === undefined) return table.columns;
  return select.map((field) => {
    const column = findColumn(table, field);
    if (column === undefined) {
      throw new QueryValidationError(ErrorCodes.ValidationUnknownProperty, `Unknown property '${field}' on '${table.exposedName}'.`);
    }
    return column;
  });
}

function findToManyNavigation(
  schema: SchemaSnapshot,
  parent: TableModel,
  navigation: string,
): { child: TableModel; fk: ForeignKeyModel } | undefined {
  for (const candidate of schema.tables) {
    for (const fk of candidate.foreignKeys) {
      if (fk.refTable === parent.exposedName && fk.navToMany === navigation) {
        return { child: candidate, fk };
      }
    }
  }
  return undefined;
}

function opSql(op: ComparisonOp): string {
  switch (op) {
    case "eq":
      return "=";
    case "ne":
      return "<>";
    case "gt":
      return ">";
    case "ge":
      return ">=";
    case "lt":
      return "<";
    case "le":
      return "<=";
    default:
      throw new NotSupportedQueryError(`Unknown operator ${op}.`);
  }
}

function escapeLike(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("%", "\\%").replaceAll("_", "\\_");
}

/** Per-compilation state: parameters, joins, alias allocation. */
class CompileContext {
  private readonly params: SqlParam[] = [];
  private readonly joinList: string[] = [];
  private readonly joinAliases = new Map<string, string>();
  private lambdaCounter = 0;

  constructor(
    readonly schema: SchemaSnapshot,
    private readonly dialect: SqlDialect,
    readonly rootTable: TableModel,
  ) {}

  get parameters(): readonly SqlParam[] {
    return this.params;
  }

  get joins(): readonly string[] {
    return this.joinList;
  }

  addParameter(value: unknown): string {
    const name = `@p${this.params.length}`;
    this.params.push({ name, value });
    return name;
  }

  nextLambdaAlias(): string {
    return `l${this.lambdaCounter++}`;
  }

  ensureJoin(
    fromAlias: string,
    fromTable: TableModel,
    fk: ForeignKeyModel,
    target: TableModel,
    qualifiedTarget: string,
  ): string {
    const key = `${fromAlias}:${fk.name}`;
    const existing = this.joinAliases.get(key);
    if (existing !== undefined) return existing;

    const alias = `t${this.joinAliases.size + 1}`;
    this.joinAliases.set(key, alias);

    const condition = fk.columns
      .map((col, i) => {
        const fromColumn = fromTable.columns.find((c) => c.exposedName === col || c.dbName === col)!;
        const refCol = fk.refColumns[i]!;
        const toColumn = target.columns.find((c) => c.exposedName === refCol || c.dbName === refCol)!;
        return `${fromAlias}.${this.dialect.quoteIdentifier(fromColumn.dbName)} = ${alias}.${this.dialect.quoteIdentifier(toColumn.dbName)}`;
      })
      .join(" AND ");

    this.joinList.push(`LEFT JOIN ${qualifiedTarget} AS ${alias} ON ${condition}`);
    return alias;
  }
}
