using EzOdata.Connectors.Abstractions;
using EzOdata.Core.Schema;
using MySqlConnector;

namespace EzOdata.Connectors.MySql;

/// <summary>information_schema-based introspection for MySQL/MariaDB (spec 04 §4).</summary>
public sealed class MySqlIntrospector : ISchemaIntrospector
{
    public async Task<SchemaSnapshot> IntrospectAsync(ConnectionSpec spec, IntrospectionOptions options, CancellationToken ct)
    {
        using var connection = new MySqlConnection(MySqlConnectorFactory.BuildConnectionString(spec, 15));
        await connection.OpenAsync(ct);

        var database = spec.Database!;

        // Tables + views
        var rawTables = new List<(string Name, bool IsView, string? Comment)>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT TABLE_NAME, TABLE_TYPE, TABLE_COMMENT
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = @db
                ORDER BY TABLE_NAME
                """;
            command.Parameters.AddWithValue("db", database);
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                var comment = reader.IsDBNull(2) ? null : reader.GetString(2);
                rawTables.Add((reader.GetString(0), reader.GetString(1) == "VIEW",
                    string.IsNullOrEmpty(comment) ? null : comment));
            }
        }

        var included = rawTables
            .Where(t => options.ExcludeTables.Count == 0 || !Core.Text.Glob.MatchesAny(t.Name, options.ExcludeTables))
            .Where(t => options.IncludeViews || !t.IsView)
            .ToList();
        var includedNames = new HashSet<string>(included.Select(t => t.Name), StringComparer.Ordinal);

        // Columns
        var columnsByTable = new Dictionary<string, List<ColumnModel>>(StringComparer.Ordinal);
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE, COLUMN_TYPE,
                       IS_NULLABLE = 'YES', CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE,
                       COLUMN_DEFAULT, EXTRA, COLUMN_COMMENT, COLUMN_KEY
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = @db
                ORDER BY TABLE_NAME, ORDINAL_POSITION
                """;
            command.Parameters.AddWithValue("db", database);
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                var tableName = reader.GetString(0);
                if (!includedNames.Contains(tableName)) continue;

                var dataType = reader.GetString(3);
                var columnType = reader.GetString(4);
                var extra = reader.IsDBNull(10) ? "" : reader.GetString(10);
                var (edmType, fallback, allowedValues) = MapType(dataType, columnType);

                if (!columnsByTable.TryGetValue(tableName, out var list))
                {
                    columnsByTable[tableName] = list = [];
                }

                var maxLength = reader.IsDBNull(6) ? (long?)null : reader.GetInt64(6);
                list.Add(new ColumnModel
                {
                    DbName = reader.GetString(1),
                    ExposedName = reader.GetString(1),
                    DbType = columnType,
                    EdmType = edmType,
                    IsFallbackType = fallback,
                    AllowedValues = allowedValues,
                    Nullable = reader.GetBoolean(5),
                    MaxLength = maxLength is > int.MaxValue ? null : (int?)maxLength,
                    Precision = reader.IsDBNull(7) ? null : (int)reader.GetInt64(7),
                    Scale = reader.IsDBNull(8) ? null : (int)reader.GetInt64(8),
                    DefaultExpression = reader.IsDBNull(9) ? null : reader.GetString(9),
                    IsAutoGenerated = extra.Contains("auto_increment", StringComparison.OrdinalIgnoreCase),
                    IsComputed = extra.Contains("GENERATED", StringComparison.OrdinalIgnoreCase),
                    Comment = reader.IsDBNull(11) || reader.GetString(11).Length == 0 ? null : reader.GetString(11),
                });
            }
        }

        // Primary keys + uniques
        var keysByTable = new Dictionary<string, List<(string Constraint, bool IsPrimary, string Column, int Ordinal)>>(StringComparer.Ordinal);
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT tc.TABLE_NAME, tc.CONSTRAINT_NAME, tc.CONSTRAINT_TYPE, kcu.COLUMN_NAME, kcu.ORDINAL_POSITION
                FROM information_schema.TABLE_CONSTRAINTS tc
                JOIN information_schema.KEY_COLUMN_USAGE kcu
                  ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
                 AND kcu.TABLE_SCHEMA = tc.TABLE_SCHEMA
                 AND kcu.TABLE_NAME = tc.TABLE_NAME
                WHERE tc.TABLE_SCHEMA = @db AND tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
                ORDER BY tc.TABLE_NAME, tc.CONSTRAINT_NAME, kcu.ORDINAL_POSITION
                """;
            command.Parameters.AddWithValue("db", database);
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                var tableName = reader.GetString(0);
                if (!includedNames.Contains(tableName)) continue;
                if (!keysByTable.TryGetValue(tableName, out var list))
                {
                    keysByTable[tableName] = list = [];
                }

                list.Add((reader.GetString(1), reader.GetString(2) == "PRIMARY KEY",
                    reader.GetString(3), reader.GetInt32(4)));
            }
        }

        // Foreign keys (ordered composite columns)
        var fksRaw = new List<(string Constraint, string Table, string Column, string RefTable, string RefColumn, int Ordinal)>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME,
                       REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME, ORDINAL_POSITION
                FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = @db AND REFERENCED_TABLE_NAME IS NOT NULL
                ORDER BY CONSTRAINT_NAME, ORDINAL_POSITION
                """;
            command.Parameters.AddWithValue("db", database);
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                fksRaw.Add((reader.GetString(0), reader.GetString(1), reader.GetString(2),
                    reader.GetString(3), reader.GetString(4), reader.GetInt32(5)));
            }
        }

        var tables = new List<TableModel>();
        foreach (var (name, isView, comment) in included)
        {
            var keys = keysByTable.TryGetValue(name, out var keyList) ? keyList : [];
            var pkColumns = keys.Where(k => k.IsPrimary).OrderBy(k => k.Ordinal).Select(k => k.Column).ToList();
            var pkSet = new HashSet<string>(pkColumns, StringComparer.Ordinal);
            var columns = columnsByTable.TryGetValue(name, out var cols) ? cols : [];
            for (var c = 0; c < columns.Count; c++)
            {
                if (pkSet.Contains(columns[c].ExposedName))
                {
                    columns[c] = columns[c] with { IsPrimaryKey = true, Nullable = false };
                }
            }

            tables.Add(new TableModel
            {
                DbSchema = "",
                DbName = name,
                ExposedName = name,
                IsView = isView,
                Writable = !isView,
                Comment = comment,
                Columns = columns,
                PrimaryKey = pkColumns,
                UniqueConstraints = keys.Where(k => !k.IsPrimary)
                    .GroupBy(k => k.Constraint)
                    .Select(g => (IReadOnlyList<string>)g.OrderBy(k => k.Ordinal).Select(k => k.Column).ToList())
                    .ToList(),
            });
        }

        // Navigations
        for (var i = 0; i < tables.Count; i++)
        {
            var table = tables[i];
            var childTaken = new HashSet<string>(table.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
            var fks = new List<ForeignKeyModel>();

            foreach (var group in fksRaw.Where(f => f.Table == table.DbName).GroupBy(f => f.Constraint).OrderBy(g => g.Key))
            {
                var refTable = group.First().RefTable;
                if (!includedNames.Contains(refTable)) continue;

                var parent = tables.First(t => t.ExposedName == refTable);
                var parentTaken = new HashSet<string>(parent.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
                foreach (var existing in parent.ForeignKeys) parentTaken.Add(existing.NavToMany);

                var ordered = group.OrderBy(g => g.Ordinal).ToList();
                var fromColumns = ordered.Select(g => g.Column).ToList();
                fks.Add(new ForeignKeyModel
                {
                    Name = group.Key,
                    Columns = fromColumns,
                    RefTable = refTable,
                    RefColumns = ordered.Select(g => g.RefColumn).ToList(),
                    NavToOne = NavigationNaming.ToOneName(fromColumns, refTable, group.Key, childTaken),
                    NavToMany = NavigationNaming.ToManyName(table.ExposedName, group.Key, parentTaken),
                });
            }

            tables[i] = table with { ForeignKeys = fks };
        }

        return new SchemaSnapshot
        {
            Engine = "mysql",
            CollectedAt = DateTimeOffset.UtcNow,
            Tables = tables.OrderBy(t => t.ExposedName, StringComparer.Ordinal).ToList(),
        };
    }

    public static (string EdmType, bool Fallback, IReadOnlyList<string>? AllowedValues) MapType(string dataType, string columnType)
    {
        if (columnType.Equals("tinyint(1)", StringComparison.OrdinalIgnoreCase))
        {
            return ("Edm.Boolean", false, null);
        }

        var unsigned = columnType.Contains("unsigned", StringComparison.OrdinalIgnoreCase);

        if (dataType.Equals("enum", StringComparison.OrdinalIgnoreCase))
        {
            // enum('a','b','c') → String + allowed values (spec 04 §6)
            var inner = columnType.Substring(columnType.IndexOf('(') + 1).TrimEnd(')');
            var values = inner.Split(',')
                .Select(v => v.Trim().Trim('\'').Replace("''", "'"))
                .ToList();
            return ("Edm.String", false, values);
        }

        return dataType.ToLowerInvariant() switch
        {
            "tinyint" => unsigned ? ("Edm.Int16", false, null) : ("Edm.Int16", false, null),
            "smallint" => unsigned ? ("Edm.Int32", false, null) : ("Edm.Int16", false, null),
            "mediumint" or "int" or "integer" => unsigned ? ("Edm.Int64", false, null) : ("Edm.Int32", false, null),
            "bigint" => ("Edm.Int64", false, null), // unsigned bigint can overflow; acceptable v1 edge
            "decimal" or "numeric" => ("Edm.Decimal", false, null),
            "float" => ("Edm.Single", false, null),
            "double" or "real" => ("Edm.Double", false, null),
            "bit" => ("Edm.Boolean", false, null),
            "char" or "varchar" or "tinytext" or "text" or "mediumtext" or "longtext" => ("Edm.String", false, null),
            "datetime" or "timestamp" => ("Edm.DateTimeOffset", false, null),
            "date" => ("Edm.Date", false, null),
            "time" => ("Edm.TimeOfDay", false, null),
            "year" => ("Edm.Int16", false, null),
            "binary" or "varbinary" or "tinyblob" or "blob" or "mediumblob" or "longblob" => ("Edm.Binary", false, null),
            "json" => ("Edm.Untyped", false, null),
            _ => ("Edm.String", true, null),
        };
    }
}
