using EzOdata.Core.Schema;
using Xunit;

namespace EzOdata.UnitTests.Schema;

public class SnapshotSerializerTests
{
    private static SchemaSnapshot Sample(DateTimeOffset? collectedAt = null, string emailMaxLength = "320") =>
        new()
        {
            Engine = "postgresql",
            CollectedAt = collectedAt ?? new DateTimeOffset(2026, 6, 12, 0, 0, 0, TimeSpan.Zero),
            Tables =
            [
                new TableModel
                {
                    DbSchema = "public",
                    DbName = "customers",
                    ExposedName = "customers",
                    Columns =
                    [
                        new ColumnModel { DbName = "id", ExposedName = "id", DbType = "integer", EdmType = "Edm.Int32", IsPrimaryKey = true, IsAutoGenerated = true },
                        new ColumnModel { DbName = "email", ExposedName = "email", DbType = "varchar", EdmType = "Edm.String", MaxLength = int.Parse(emailMaxLength) },
                    ],
                    PrimaryKey = ["id"],
                },
                new TableModel
                {
                    DbSchema = "public",
                    DbName = "orders",
                    ExposedName = "orders",
                    Columns =
                    [
                        new ColumnModel { DbName = "id", ExposedName = "id", DbType = "bigint", EdmType = "Edm.Int64", IsPrimaryKey = true },
                        new ColumnModel { DbName = "customer_id", ExposedName = "customer_id", DbType = "integer", EdmType = "Edm.Int32" },
                    ],
                    PrimaryKey = ["id"],
                    ForeignKeys =
                    [
                        new ForeignKeyModel
                        {
                            Name = "fk_orders_customer",
                            Columns = ["customer_id"],
                            RefTable = "customers",
                            RefColumns = ["id"],
                            NavToOne = "customer",
                            NavToMany = "orders",
                        },
                    ],
                },
            ],
        };

    [Fact]
    public void Roundtrips_through_json()
    {
        var snapshot = Sample();
        var restored = SnapshotSerializer.Deserialize(SnapshotSerializer.Serialize(snapshot));

        Assert.Equal(snapshot.Tables.Count, restored.Tables.Count);
        Assert.Equal("customers", restored.Tables[0].ExposedName);
        Assert.Equal(["id"], restored.Tables[0].PrimaryKey);
        Assert.Equal("customer", restored.Tables[1].ForeignKeys[0].NavToOne);
    }

    [Fact]
    public void Hash_ignores_collection_timestamp()
    {
        var a = Sample(collectedAt: new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero));
        var b = Sample(collectedAt: new DateTimeOffset(2026, 6, 6, 6, 6, 6, TimeSpan.Zero));

        Assert.Equal(SnapshotSerializer.ComputeHash(a), SnapshotSerializer.ComputeHash(b));
    }

    [Fact]
    public void Hash_is_independent_of_table_order()
    {
        var a = Sample();
        var b = a with { Tables = a.Tables.Reverse().ToList() };

        Assert.Equal(SnapshotSerializer.ComputeHash(a), SnapshotSerializer.ComputeHash(b));
    }

    [Fact]
    public void Hash_changes_when_schema_changes()
    {
        Assert.NotEqual(
            SnapshotSerializer.ComputeHash(Sample(emailMaxLength: "320")),
            SnapshotSerializer.ComputeHash(Sample(emailMaxLength: "100")));
    }

    [Fact]
    public void Counts_distinguish_views()
    {
        var snapshot = Sample();
        var withView = snapshot with
        {
            Tables = [.. snapshot.Tables, new TableModel
            {
                DbSchema = "public", DbName = "v_totals", ExposedName = "v_totals",
                IsView = true, Writable = false,
            }],
        };

        Assert.Equal(2, withView.TableCount);
        Assert.Equal(1, withView.ViewCount);
    }
}
