import type { SchemaIntrospector, ConnectionSpec, IntrospectionOptions } from "../contracts.js";
import type { ColumnModel, ForeignKeyModel, SchemaSnapshot, TableModel } from "../../core/schema.js";
import { createKnex, extractRawRows } from "../knex-helpers.js";
import { toOneName, toManyName } from "../navigation-naming.js";

/**
 * Pragma-based introspection for SQLite (port of SqliteIntrospector.cs, spec 04 §4):
 * table_xinfo, foreign_key_list, index_list.
 */
export class SqliteIntrospector implements SchemaIntrospector {
  /** SQLite declared type → EDM type (port of SqliteIntrospector.MapType). */
  static mapType(declared: string): { edmType: string; isFallback: boolean } {
    const upper = declared.toUpperCase();
    if (upper.includes("BOOL")) return { edmType: "Edm.Boolean", isFallback: false };
    if (upper.includes("DATETIME") || upper.includes("TIMESTAMP")) return { edmType: "Edm.DateTimeOffset", isFallback: false };
    if (upper.includes("DATE")) return { edmType: "Edm.Date", isFallback: false };
    if (upper.includes("TIME")) return { edmType: "Edm.TimeOfDay", isFallback: false };
    if (upper.includes("GUID") || upper.includes("UUID")) return { edmType: "Edm.Guid", isFallback: false };
    if (upper.includes("JSON")) return { edmType: "Edm.Untyped", isFallback: false };
    if (upper.includes("INT")) return { edmType: "Edm.Int64", isFallback: false };
    if (upper.includes("CHAR") || upper.includes("TEXT") || upper.includes("CLOB")) return { edmType: "Edm.String", isFallback: false };
    if (upper.includes("REAL") || upper.includes("FLOA") || upper.includes("DOUB")) return { edmType: "Edm.Double", isFallback: false };
    if (upper.includes("DEC") || upper.includes("NUMERIC") || upper.includes("MONEY")) return { edmType: "Edm.Decimal", isFallback: false };
    if (upper.includes("BLOB") || upper.length === 0) return { edmType: "Edm.Binary", isFallback: false };
    return { edmType: "Edm.String", isFallback: true };
  }

  async introspect(spec: ConnectionSpec, options: IntrospectionOptions, _signal?: AbortSignal): Promise<SchemaSnapshot> {
    const db = createKnex(spec, "better-sqlite3");
    try {
      const masterResult = await db.raw(
        `SELECT name, type FROM sqlite_master WHERE type IN ('table', 'view') AND name NOT LIKE 'sqlite_%' ORDER BY name`,
      );
      const rawTables = extractRawRows(masterResult, "better-sqlite3").map((r) => ({
        name: r.name as string,
        isView: (r.type as string) === "view",
      }));

      const included = rawTables
        .filter((t) => options.excludeTables.length === 0 || !options.excludeTables.some((p) => matchGlob(t.name, p)))
        .filter((t) => options.includeViews || !t.isView);

      const tables: TableModel[] = [];
      for (const { name, isView } of included) {
        const xinfo = await db.raw(`PRAGMA table_xinfo(${quoteId(name)})`);
        const infoRows = extractRawRows(xinfo, "better-sqlite3");

        const columns = [];
        const pkOrder: Array<{ col: string; ord: number }> = [];

        for (const r of infoRows) {
          const hidden = Number(r.hidden);
          if (hidden === 1) continue; // skip hidden columns
          const colName = r.name as string;
          const declared = (r.type as string | null) ?? "";
          const notNull = Number(r.notnull) === 1;
          const pk = Number(r.pk);
          const { edmType, isFallback } = SqliteIntrospector.mapType(declared);
          const col: ColumnModel = {
            dbName: colName,
            exposedName: colName,
            dbType: declared.length === 0 ? "blob" : declared.toLowerCase(),
            edmType,
            isFallbackType: isFallback,
            nullable: !notNull && pk === 0,
            isPrimaryKey: pk > 0,
            isAutoGenerated: false,
            isComputed: hidden === 2 || hidden === 3,
          };
          const dflt = r.dflt_value as string | null;
          if (dflt !== null) (col as unknown as Record<string, unknown>)["defaultExpression"] = dflt;
          columns.push(col);
          if (pk > 0) pkOrder.push({ col: colName, ord: pk });
        }

        const primaryKey = pkOrder.sort((a, b) => a.ord - b.ord).map((p) => p.col);

        // Mark single INTEGER PK as auto-generated (rowid alias)
        if (primaryKey.length === 1 && !isView) {
          const pkIdx = columns.findIndex((c) => c.exposedName === primaryKey[0]);
          if (pkIdx >= 0 && (columns[pkIdx]!.edmType === "Edm.Int64" || columns[pkIdx]!.edmType === "Edm.Int32")) {
            columns[pkIdx] = { ...columns[pkIdx]!, isAutoGenerated: true };
          }
        }

        const uniques: string[][] = [];
        if (!isView) {
          const indexList = await db.raw(`PRAGMA index_list(${quoteId(name)})`);
          const uniqueIndexNames: string[] = [];
          for (const r of extractRawRows(indexList, "better-sqlite3")) {
            if (Number(r.unique) === 1 && (r.origin as string) === "u") {
              uniqueIndexNames.push(r.name as string);
            }
          }
          for (const indexName of uniqueIndexNames) {
            const indexInfo = await db.raw(`PRAGMA index_info(${quoteId(indexName)})`);
            const cols = extractRawRows(indexInfo, "better-sqlite3")
              .filter((r) => r.name != null)
              .map((r) => r.name as string);
            if (cols.length > 0) uniques.push(cols);
          }
        }

        tables.push({
          dbSchema: "",
          dbName: name,
          exposedName: name,
          isView,
          writable: !isView,
          columns,
          primaryKey,
          uniqueConstraints: uniques,
          foreignKeys: [],
        });
      }

      // Second pass: attach FKs
      const includedNames = new Set(tables.map((t) => t.exposedName));
      for (let i = 0; i < tables.length; i++) {
        const t = tables[i]!;
        if (t.isView) continue;

        const fkList = await db.raw(`PRAGMA foreign_key_list(${quoteId(t.dbName)})`);
        const raw = extractRawRows(fkList, "better-sqlite3").map((r) => ({
          id: Number(r.id),
          refTable: r.table as string,
          from: r.from as string,
          to: (r.to as string | null) ?? "",
        }));

        const childTaken = new Set(t.columns.map((c) => c.exposedName));
        const fks: ForeignKeyModel[] = [];

        const grouped = groupBy(raw, (r) => String(r.id));
        for (const [idStr, group] of Object.entries(grouped).sort(([a], [b]) => Number(a) - Number(b))) {
          const refTable = group[0]!.refTable;
          if (!includedNames.has(refTable)) continue;
          const parent = tables.find((p) => p.exposedName === refTable)!;
          const parentTaken = new Set([...parent.columns.map((c) => c.exposedName), ...parent.foreignKeys.map((f) => f.navToMany)]);
          const fkName = `fk_${t.dbName}_${idStr}`;
          const fromColumns = group.map((g) => g.from);
          const toColumns = group.map((g) => g.to || parent.primaryKey[0] || "");
          fks.push({
            name: fkName,
            columns: fromColumns,
            refTable,
            refColumns: toColumns,
            navToOne: toOneName(fromColumns, refTable, fkName, childTaken),
            navToMany: toManyName(t.exposedName, fkName, parentTaken),
          });
        }

        tables[i] = { ...t, foreignKeys: fks };
      }

      return {
        version: 1,
        engine: "sqlite",
        collectedAt: new Date().toISOString(),
        tables: [...tables].sort((a, b) => a.exposedName.localeCompare(b.exposedName)),
      };
    } finally {
      await db.destroy();
    }
  }
}

function quoteId(name: string): string {
  return `"${name.replaceAll('"', '""')}"`;
}

function matchGlob(value: string, pattern: string): boolean {
  const re = new RegExp("^" + pattern.replace(/\*/g, ".*").replace(/\?/g, ".") + "$", "i");
  return re.test(value);
}

function groupBy<T>(arr: T[], key: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const k = key(item);
    if (!result[k]) result[k] = [];
    result[k]!.push(item);
  }
  return result;
}
