using System.Text.Json.Serialization;

namespace EzOdata.Core.Schema;

/// <summary>
/// Normalized, engine-agnostic schema snapshot (spec 04 §5).
/// This is the single source of truth for EDM models, SQL compilation, docs, and MCP.
/// </summary>
public sealed record SchemaSnapshot
{
    public int Version { get; init; } = 1;
    public required string Engine { get; init; }
    public DateTimeOffset CollectedAt { get; init; }
    public IReadOnlyList<TableModel> Tables { get; init; } = [];

    [JsonIgnore]
    public int TableCount => Tables.Count(t => !t.IsView);

    [JsonIgnore]
    public int ViewCount => Tables.Count(t => t.IsView);

    public TableModel? FindTable(string exposedName) =>
        Tables.FirstOrDefault(t => string.Equals(t.ExposedName, exposedName, StringComparison.Ordinal));
}

public sealed record TableModel
{
    public required string DbSchema { get; init; }
    public required string DbName { get; init; }
    public required string ExposedName { get; init; }
    public bool IsView { get; init; }
    public bool Writable { get; init; } = true;
    public string? Comment { get; init; }
    public IReadOnlyList<ColumnModel> Columns { get; init; } = [];
    public IReadOnlyList<string> PrimaryKey { get; init; } = [];
    public IReadOnlyList<IReadOnlyList<string>> UniqueConstraints { get; init; } = [];
    public IReadOnlyList<ForeignKeyModel> ForeignKeys { get; init; } = [];

    [JsonIgnore]
    public bool HasKey => PrimaryKey.Count > 0;

    public ColumnModel? FindColumn(string exposedName) =>
        Columns.FirstOrDefault(c => string.Equals(c.ExposedName, exposedName, StringComparison.Ordinal));
}

public sealed record ColumnModel
{
    public required string DbName { get; init; }
    public required string ExposedName { get; init; }
    public required string DbType { get; init; }

    /// <summary>EDM type per the total mapping of spec 04 §6, e.g. "Edm.Int32".</summary>
    public required string EdmType { get; init; }

    public bool Nullable { get; init; }
    public int? MaxLength { get; init; }
    public int? Precision { get; init; }
    public int? Scale { get; init; }
    public bool IsPrimaryKey { get; init; }
    public bool IsAutoGenerated { get; init; }
    public bool IsComputed { get; init; }
    public string? DefaultExpression { get; init; }
    public string? Comment { get; init; }

    /// <summary>Set when EdmType is a fallback (unmapped db type exposed as Edm.String, spec 04 CON-8).</summary>
    public bool IsFallbackType { get; init; }

    /// <summary>Enum/check-constraint values where the engine exposes them (spec 04 §6).</summary>
    public IReadOnlyList<string>? AllowedValues { get; init; }
}

public sealed record ForeignKeyModel
{
    public required string Name { get; init; }
    public IReadOnlyList<string> Columns { get; init; } = [];
    public required string RefTable { get; init; }
    public IReadOnlyList<string> RefColumns { get; init; } = [];

    /// <summary>Navigation property name on the child pointing at the parent (spec 04 §5.3).</summary>
    public required string NavToOne { get; init; }

    /// <summary>Navigation property name on the parent pointing at children.</summary>
    public required string NavToMany { get; init; }
}
