// <auto-generated />
using System;
using EzOdata.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EzOdata.Data.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("EzOdata.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.AppEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AllowedOriginsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_origins_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("McpEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mcp_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("RequireUserSession")
                        .HasColumnType("INTEGER")
                        .HasColumnName("require_user_session");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<long?>("AppId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detail_json");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Resource")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource");

                    b.Property<long?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("AppId", "OccurredAt");

                    b.HasIndex("ServiceId", "OccurredAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.FieldPolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("FieldPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("field_pattern");

                    b.Property<string>("MaskValue")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("mask_value");

                    b.Property<long>("RoleServiceAccessId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_service_access_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleServiceAccessId");

                    b.ToTable("field_policies", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.JobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RateLimitPolicyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_requests");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<long?>("ScopeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Verbs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verbs");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("window_seconds");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId");

                    b.ToTable("rate_limit_policies", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("BypassDataRules")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bypass_data_rules");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RoleServiceAccessEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("effect");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("ResourcePattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_pattern");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<string>("RowFilter")
                        .HasColumnType("TEXT")
                        .HasColumnName("row_filter");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<int>("Verbs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("verbs");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ServiceId");

                    b.ToTable("role_service_access", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.SchemaSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IntrospectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("introspected_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_current");

                    b.Property<long>("ServiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("TableCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_count");

                    b.Property<string>("VersionHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_hash");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasFilter("is_current = 1");

                    b.ToTable("schema_snapshots", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.ServiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_display");

                    b.Property<string>("ConnectionEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_encrypted");

                    b.Property<string>("ConnectionFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_fingerprint");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("options_json");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<int?>("SchemaRefreshMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_refresh_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_detail");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("is_deleted = 0");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.SystemSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Key");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.UserRoleEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("EzOdata.Data.Entities.ApiKeyEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.AppEntity", "App")
                        .WithMany("Keys")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.AppEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.FieldPolicyEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.RoleServiceAccessEntity", "Access")
                        .WithMany("FieldPolicies")
                        .HasForeignKey("RoleServiceAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RoleServiceAccessEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.RoleEntity", "Role")
                        .WithMany("Access")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.SchemaSnapshotEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.ServiceEntity", "Service")
                        .WithMany("Snapshots")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("EzOdata.Data.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EzOdata.Data.Entities.UserEntity", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.AppEntity", b =>
                {
                    b.Navigation("Keys");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("Access");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.RoleServiceAccessEntity", b =>
                {
                    b.Navigation("FieldPolicies");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.ServiceEntity", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EzOdata.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
