import { describe, expect, it } from "vitest";
import { QueryValidationError } from "../../../src/connectors/contracts.js";
import { MySqlDialect } from "../../../src/connectors/dialects/mysql.js";
import { PostgreSqlDialect } from "../../../src/connectors/dialects/postgres.js";
import { SqlServerDialect } from "../../../src/connectors/dialects/sqlserver.js";
import { SqliteDialect } from "../../../src/connectors/dialects/sqlite.js";
import { WriteSqlCompiler } from "../../../src/connectors/sql/write-compiler.js";
import { comparison, constant, fieldRef } from "../../../src/core/query.js";
import { col, snapshot, table } from "../../helpers/schema.js";

/**
 * Write SQL compiler unit tests (port of DialectMatrixTests.cs insert/update/delete sections
 * + NFR-3 injection safety, spec 04 §7.3).
 */
describe("WriteSqlCompiler", () => {
  const TAINT = "EZTAINT_WRITE_8a2f";

  const schema = snapshot("any", [
    table({
      dbName: "orders",
      primaryKey: ["id"],
      columns: [
        col("id", "Edm.Int64", { isPrimaryKey: true, isAutoGenerated: true }),
        col("status", "Edm.String"),
        col("total", "Edm.Decimal"),
        col("created_at", "Edm.DateTimeOffset"),
      ],
    }),
  ]);

  const ordersTable = schema.tables[0]!;

  const pg = new WriteSqlCompiler(new PostgreSqlDialect());
  const ss = new WriteSqlCompiler(new SqlServerDialect());
  const my = new WriteSqlCompiler(new MySqlDialect());
  const sq = new WriteSqlCompiler(new SqliteDialect());

  // ---- INSERT ----

  it("compiles INSERT without RETURNING (MySQL none strategy)", () => {
    const c = my.compileInsert(schema, ordersTable, { values: { status: "open" }, children: {} }, false);
    expect(c.sql).toBe("INSERT INTO `orders` (`status`) VALUES (@p0)");
    expect(c.parameters).toHaveLength(1);
    expect(c.parameters[0]!.value).toBe("open");
  });

  it("compiles INSERT with RETURNING suffix (PostgreSQL)", () => {
    const c = pg.compileInsert(schema, ordersTable, { values: { status: "x" }, children: {} }, true);
    expect(c.sql).toContain('INSERT INTO "orders" ("status") VALUES (@p0) RETURNING');
    expect(c.sql).not.toContain("OUTPUT");
  });

  it("compiles INSERT with OUTPUT INSERTED (SQL Server)", () => {
    const c = ss.compileInsert(
      schema,
      ordersTable,
      { values: { status: "open" }, children: {} },
      true,
    );
    expect(c.sql).toContain(") OUTPUT");
    expect(c.sql).toContain("OUTPUT INSERTED.[id] AS [id]");
    expect(c.sql).toContain("VALUES (@p0)");
    expect(c.sql).not.toContain("RETURNING");
  });

  it("compiles INSERT with RETURNING suffix (SQLite)", () => {
    const c = sq.compileInsert(schema, ordersTable, { values: { status: "x" }, children: {} }, true);
    expect(c.sql).toContain("RETURNING");
  });

  it("compiles INSERT with DEFAULT VALUES when payload is empty", () => {
    const c = pg.compileInsert(schema, ordersTable, { values: {}, children: {} }, false);
    expect(c.sql).toBe('INSERT INTO "orders" DEFAULT VALUES');
    expect(c.parameters).toHaveLength(0);
  });

  it("compiles INSERT with multiple columns", () => {
    const c = pg.compileInsert(
      schema,
      ordersTable,
      { values: { status: "open", total: 99.99 }, children: {} },
      false,
    );
    expect(c.sql).toContain('"status"');
    expect(c.sql).toContain('"total"');
    expect(c.sql).toContain("@p0");
    expect(c.sql).toContain("@p1");
    expect(c.parameters).toHaveLength(2);
  });

  it("throws QueryValidationError for unknown column in INSERT", () => {
    expect(() =>
      pg.compileInsert(schema, ordersTable, { values: { nope: "x" }, children: {} }, false),
    ).toThrow(QueryValidationError);
  });

  // ---- UPDATE ----

  it("compiles UPDATE with key predicate", () => {
    const c = pg.compileUpdate(
      schema,
      ordersTable,
      {
        serviceName: "s",
        table: "orders",
        kind: "update",
        records: [{ values: { status: "shipped" }, children: {} }],
        key: { values: { id: 5 } },
      },
      false,
    );
    expect(c.sql).toBe('UPDATE "orders" SET "status" = @p0 WHERE "id" = @p1');
    expect(c.parameters[0]!.value).toBe("shipped");
    expect(c.parameters[1]!.value).toBe(5);
  });

  it("compiles UPDATE with RETURNING suffix (PostgreSQL)", () => {
    const c = pg.compileUpdate(
      schema,
      ordersTable,
      {
        serviceName: "s",
        table: "orders",
        kind: "update",
        records: [{ values: { status: "shipped" }, children: {} }],
        key: { values: { id: 1 } },
      },
      true,
    );
    expect(c.sql).toContain("RETURNING");
    expect(c.sql).not.toContain("OUTPUT");
  });

  it("compiles UPDATE with OUTPUT INSERTED (SQL Server)", () => {
    const c = ss.compileUpdate(
      schema,
      ordersTable,
      {
        serviceName: "s",
        table: "orders",
        kind: "update",
        records: [{ values: { status: "shipped" }, children: {} }],
        key: { values: { id: 1 } },
      },
      true,
    );
    expect(c.sql).toContain("OUTPUT INSERTED");
    expect(c.sql).not.toContain("RETURNING");
  });

  it("compiles UPDATE with precondition filter", () => {
    const c = pg.compileUpdate(
      schema,
      ordersTable,
      {
        serviceName: "s",
        table: "orders",
        kind: "update",
        records: [{ values: { status: "shipped" }, children: {} }],
        key: { values: { id: 3 } },
        precondition: comparison(fieldRef("status"), "eq", constant("open")),
      },
      false,
    );
    expect(c.sql).toContain("WHERE");
    expect(c.sql).toContain('"id" = @p1');
    expect(c.sql).toContain('"status" = @p2');
    expect(c.parameters).toHaveLength(3);
  });

  it("throws when updating a PK column", () => {
    expect(() =>
      pg.compileUpdate(
        schema,
        ordersTable,
        {
          serviceName: "s",
          table: "orders",
          kind: "update",
          records: [{ values: { id: 999 }, children: {} }],
          key: { values: { id: 1 } },
        },
        false,
      ),
    ).toThrow(QueryValidationError);
  });

  it("throws when UPDATE payload is empty", () => {
    expect(() =>
      pg.compileUpdate(
        schema,
        ordersTable,
        {
          serviceName: "s",
          table: "orders",
          kind: "update",
          records: [{ values: {}, children: {} }],
          key: { values: { id: 1 } },
        },
        false,
      ),
    ).toThrow(QueryValidationError);
  });

  it("throws when UPDATE has no key or precondition (safety guard)", () => {
    expect(() =>
      pg.compileUpdate(
        schema,
        ordersTable,
        {
          serviceName: "s",
          table: "orders",
          kind: "update",
          records: [{ values: { status: "x" }, children: {} }],
        },
        false,
      ),
    ).toThrow(QueryValidationError);
  });

  it("throws for unknown property in UPDATE", () => {
    expect(() =>
      pg.compileUpdate(
        schema,
        ordersTable,
        {
          serviceName: "s",
          table: "orders",
          kind: "update",
          records: [{ values: { nope: "x" }, children: {} }],
          key: { values: { id: 1 } },
        },
        false,
      ),
    ).toThrow(QueryValidationError);
  });

  // ---- DELETE ----

  it("compiles DELETE with key predicate", () => {
    const c = pg.compileDelete(schema, ordersTable, {
      serviceName: "s",
      table: "orders",
      kind: "delete",
      records: [],
      key: { values: { id: 7 } },
    });
    expect(c.sql).toBe('DELETE FROM "orders" WHERE "id" = @p0');
    expect(c.parameters[0]!.value).toBe(7);
  });

  it("compiles DELETE with MySQL quoting", () => {
    const c = my.compileDelete(schema, ordersTable, {
      serviceName: "s",
      table: "orders",
      kind: "delete",
      records: [],
      key: { values: { id: 3 } },
    });
    expect(c.sql).toBe("DELETE FROM `orders` WHERE `id` = @p0");
  });

  it("throws DELETE without key or precondition", () => {
    expect(() =>
      pg.compileDelete(schema, ordersTable, {
        serviceName: "s",
        table: "orders",
        kind: "delete",
        records: [],
      }),
    ).toThrow(QueryValidationError);
  });

  // ---- Safety invariant ----

  it("keeps injection payloads in parameters for INSERT", () => {
    const payloads = ["'; DROP TABLE orders; --", "1 OR 1=1", '" OR ""="'];
    for (const payload of payloads) {
      const c = pg.compileInsert(schema, ordersTable, { values: { status: payload }, children: {} }, false);
      expect(c.sql).not.toContain("DROP");
      expect(c.sql).not.toContain(payload);
      expect(c.parameters[0]!.value).toBe(payload);
    }
  });

  it("keeps injection payloads in parameters for UPDATE", () => {
    const c = pg.compileUpdate(
      schema,
      ordersTable,
      {
        serviceName: "s",
        table: "orders",
        kind: "update",
        records: [{ values: { status: TAINT }, children: {} }],
        key: { values: { id: 1 } },
      },
      false,
    );
    expect(c.sql).not.toContain(TAINT);
    expect(c.parameters[0]!.value).toBe(TAINT);
    expect(c.sql).toContain("@p0");
    expect(c.sql).toContain("@p1");
  });
});
