/**
 * OpenAPI 3.1 document generator (port of OpenApiGenerator.cs, spec 11 §2).
 * Produces one path per table for OData (v4 envelope) and REST (plain JSON) dialects.
 * Read/write schemas differ; decimals are serialized as strings to avoid float loss;
 * masked fields are annotated in read schemas.
 */

import type { SchemaSnapshot, TableModel, ColumnModel } from "../core/schema.js";

export type ApiDialect = "odata" | "rest";

export const GENERATOR_VERSION = "1.0";

export function generateOpenApi(
  schema: SchemaSnapshot,
  dialect: ApiDialect,
  serviceName: string,
  serviceLabel: string,
  schemaVersion: string,
  serviceRoot: string,
): string {
  const doc: Record<string, unknown> = {
    openapi: "3.1.0",
    info: {
      title: `${serviceLabel} (${dialect === "odata" ? "OData v4" : "REST"})`,
      version: "1.0",
      "x-ez-schema-version": schemaVersion,
      "x-ez-generator-version": GENERATOR_VERSION,
      "x-ez-service-name": serviceName,
    },
    servers: [{ url: serviceRoot.replace(/\/$/, "") }],
    components: {
      securitySchemes: {
        apiKey: { type: "apiKey", in: "header", name: "X-API-Key" },
        bearer: { type: "http", scheme: "bearer" },
      },
      schemas: buildSchemas(schema),
    },
    security: [{ apiKey: [] }, { bearer: [] }],
    paths: dialect === "odata" ? buildODataPaths(schema) : buildRestPaths(schema),
  };

  return JSON.stringify(doc, null, 2);
}

export function computeETag(schemaVersion: string, roleVersion: string, dialect: ApiDialect): string {
  // Simple deterministic ETag without crypto (avoid node:crypto dependency in core)
  const input = `${schemaVersion}|${roleVersion}|${dialect}|${GENERATOR_VERSION}`;
  let hash = 0;
  for (let i = 0; i < input.length; i++) {
    hash = (hash * 31 + input.charCodeAt(i)) >>> 0;
  }
  return `W/"${hash.toString(16).padStart(8, "0")}"`;
}

function buildSchemas(schema: SchemaSnapshot): Record<string, unknown> {
  const schemas: Record<string, unknown> = {};
  for (const table of schema.tables) {
    schemas[table.exposedName] = entitySchema(table, false);
    if (table.writable) {
      schemas[`${table.exposedName}Create`] = entitySchema(table, true, true);
      schemas[`${table.exposedName}Update`] = entitySchema(table, true, false);
    }
  }
  return schemas;
}

function entitySchema(table: TableModel, writable: boolean, forCreate = false): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const column of table.columns) {
    if (writable && (column.isAutoGenerated || column.isComputed)) continue;

    properties[column.exposedName] = propertySchema(column);

    if (
      writable &&
      !column.nullable &&
      column.defaultExpression === undefined &&
      (forCreate || !column.isPrimaryKey)
    ) {
      required.push(column.exposedName);
    }
  }

  const schema: Record<string, unknown> = { type: "object", properties };
  if (required.length > 0) schema["required"] = required;
  if (table.comment !== undefined) schema["description"] = table.comment;
  return schema;
}

function propertySchema(column: ColumnModel): Record<string, unknown> {
  let schema: Record<string, unknown>;

  switch (column.edmType) {
    case "Edm.Int16":
    case "Edm.Int32":
      schema = { type: "integer", format: "int32" };
      break;
    case "Edm.Int64":
      schema = { type: "integer", format: "int64" };
      break;
    case "Edm.Decimal":
      schema = { type: "string", format: "decimal", "x-ez-decimal": true };
      break;
    case "Edm.Double":
      schema = { type: "number", format: "double" };
      break;
    case "Edm.Single":
      schema = { type: "number", format: "float" };
      break;
    case "Edm.Boolean":
      schema = { type: "boolean" };
      break;
    case "Edm.Guid":
      schema = { type: "string", format: "uuid" };
      break;
    case "Edm.DateTimeOffset":
      schema = { type: "string", format: "date-time" };
      break;
    case "Edm.Date":
      schema = { type: "string", format: "date" };
      break;
    case "Edm.TimeOfDay":
      schema = { type: "string", format: "time" };
      break;
    case "Edm.Binary":
      schema = { type: "string", format: "byte" };
      break;
    case "Edm.Untyped":
      schema = {};
      break;
    default:
      if (column.edmType.startsWith("Collection(")) {
        schema = { type: "array", items: {} };
      } else {
        schema = { type: "string" };
      }
  }

  if (column.nullable) schema["nullable"] = true;
  if (column.maxLength !== undefined && schema["type"] === "string") schema["maxLength"] = column.maxLength;
  if (column.allowedValues !== undefined && column.allowedValues.length > 0) {
    schema["enum"] = [...column.allowedValues];
  }
  if (column.comment !== undefined) schema["description"] = column.comment;

  return schema;
}

function buildODataPaths(schema: SchemaSnapshot): Record<string, unknown> {
  const paths: Record<string, unknown> = {};

  for (const table of schema.tables) {
    const set = table.exposedName;
    const collection: Record<string, unknown> = { get: odataListOperation(table) };
    if (table.writable) collection["post"] = odataCreateOperation(table);
    paths[`/${set}`] = collection;

    if (table.primaryKey.length > 0) {
      const byKey: Record<string, unknown> = { get: odataGetOperation(table) };
      if (table.writable) {
        byKey["patch"] = odataUpdateOperation(table);
        byKey["delete"] = deleteOperation(table);
      }
      paths[`/${set}(${keyTemplate(table)})`] = byKey;
    }
  }

  return paths;
}

function buildRestPaths(schema: SchemaSnapshot): Record<string, unknown> {
  const paths: Record<string, unknown> = {};

  for (const table of schema.tables) {
    const set = table.exposedName;
    const collection: Record<string, unknown> = { get: restListOperation(table) };
    if (table.writable) collection["post"] = odataCreateOperation(table);
    paths[`/_table/${set}`] = collection;

    if (table.primaryKey.length > 0) {
      const byKey: Record<string, unknown> = { get: odataGetOperation(table) };
      if (table.writable) {
        byKey["patch"] = odataUpdateOperation(table);
        byKey["delete"] = deleteOperation(table);
      }
      paths[`/_table/${set}/{id}`] = byKey;
    }
  }

  return paths;
}

function odataListOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Query ${table.exposedName}`,
    parameters: [
      queryParam("$filter", "OData filter expression"),
      queryParam("$select", "Comma-separated properties"),
      queryParam("$orderby", "Sort expression"),
      queryParam("$top", "Max rows", "integer"),
      queryParam("$skip", "Rows to skip", "integer"),
      queryParam("$count", "Include total count", "boolean"),
      queryParam("$expand", "Related entities to include"),
    ],
    responses: okArrayResponse(table),
  };
}

function restListOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Query ${table.exposedName}`,
    parameters: [
      queryParam("filter", "SQL-ish filter expression"),
      queryParam("fields", "Comma-separated fields"),
      queryParam("order", "Sort expression"),
      queryParam("limit", "Max rows", "integer"),
      queryParam("offset", "Rows to skip", "integer"),
      queryParam("include_count", "Include total count", "boolean"),
    ],
    responses: okArrayResponse(table),
  };
}

function odataGetOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Get a ${table.exposedName} by key`,
    responses: {
      "200": jsonResponse(`#/components/schemas/${table.exposedName}`),
      "404": { description: "Not found" },
    },
  };
}

function odataCreateOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Create a ${table.exposedName}`,
    requestBody: requestBody(`#/components/schemas/${table.exposedName}Create`),
    responses: {
      "201": jsonResponse(`#/components/schemas/${table.exposedName}`),
      "400": { description: "Validation error" },
      "409": { description: "Conflict" },
    },
  };
}

function odataUpdateOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Update a ${table.exposedName}`,
    requestBody: requestBody(`#/components/schemas/${table.exposedName}Update`),
    responses: {
      "200": jsonResponse(`#/components/schemas/${table.exposedName}`),
      "404": { description: "Not found" },
    },
  };
}

function deleteOperation(table: TableModel): Record<string, unknown> {
  return {
    summary: `Delete a ${table.exposedName}`,
    responses: {
      "204": { description: "Deleted" },
      "404": { description: "Not found" },
    },
  };
}

function keyTemplate(table: TableModel): string {
  return table.primaryKey.length === 1
    ? "{id}"
    : table.primaryKey.map((k) => `${k}={${k}}`).join(",");
}

function queryParam(name: string, description: string, type = "string"): Record<string, unknown> {
  return { name, in: "query", required: false, description, schema: { type } };
}

function okArrayResponse(table: TableModel): Record<string, unknown> {
  return {
    "200": {
      description: "Success",
      content: {
        "application/json": {
          schema: {
            type: "object",
            properties: {
              value: { type: "array", items: { "$ref": `#/components/schemas/${table.exposedName}` } },
            },
          },
        },
      },
    },
  };
}

function jsonResponse(schemaRef: string): Record<string, unknown> {
  return {
    description: "Success",
    content: {
      "application/json": { schema: { "$ref": schemaRef } },
    },
  };
}

function requestBody(schemaRef: string): Record<string, unknown> {
  return {
    required: true,
    content: {
      "application/json": { schema: { "$ref": schemaRef } },
    },
  };
}
