/**
 * JSON write payload → typed RecordPayload (port of PayloadBinder.cs, spec 05 §5.1):
 * strict coercion (no silent string→int), unknown properties rejected,
 * auto-generated/computed columns rejected, enum allowed-values enforced.
 */

import { ErrorCodes } from "../core/errors.js";
import type { SchemaSnapshot, TableModel, ColumnModel } from "../core/schema.js";
import type { RecordPayload } from "../core/write.js";

export class BindError extends Error {
  readonly errorCode: string;

  constructor(errorCode: string, message: string) {
    super(message);
    this.name = "BindError";
    this.errorCode = errorCode;
  }
}

export class PayloadBinder {
  static bind(
    json: unknown,
    table: TableModel,
    schema: SchemaSnapshot,
    opts: { allowDeepInsert?: boolean; isReplace?: boolean } = {},
  ): RecordPayload {
    const { allowDeepInsert = false, isReplace = false } = opts;

    if (typeof json !== "object" || json === null || Array.isArray(json)) {
      throw new BindError(ErrorCodes.ValidationInvalidValue, "Record payload must be a JSON object.");
    }

    const values: Record<string, unknown> = {};
    const children: Record<string, readonly RecordPayload[]> = {};
    const obj = json as Record<string, unknown>;

    for (const [propName, propValue] of Object.entries(obj)) {
      if (propName.startsWith("@")) continue; // OData control info

      const column = table.columns.find((c) => c.exposedName === propName);
      if (column !== undefined) {
        if (column.isAutoGenerated || column.isComputed) {
          throw new BindError(
            ErrorCodes.ValidationInvalidValue,
            `Property '${propName}' is generated by the database and cannot be written.`,
          );
        }
        values[propName] = coerce(propValue, column);
        continue;
      }

      // Deep insert: to-many navigation with array payload
      const childTable = findChildByNav(schema, table, propName);
      if (childTable !== undefined && Array.isArray(propValue)) {
        if (!allowDeepInsert) {
          throw new BindError(
            ErrorCodes.ValidationInvalidValue,
            `Nested collection '${propName}' is only supported on create (deep insert).`,
          );
        }
        children[propName] = (propValue as unknown[]).map((child) =>
          PayloadBinder.bind(child, childTable, schema, { allowDeepInsert: false }),
        );
        continue;
      }

      throw new BindError(
        ErrorCodes.ValidationUnknownProperty,
        `Unknown property '${propName}' on '${table.exposedName}'.`,
      );
    }

    if (isReplace) {
      for (const column of table.columns) {
        if (column.isPrimaryKey || column.isAutoGenerated || column.isComputed) continue;
        if (Object.prototype.hasOwnProperty.call(values, column.exposedName)) continue;

        if (column.nullable) {
          values[column.exposedName] = null;
        } else if (column.defaultExpression === undefined) {
          throw new BindError(
            ErrorCodes.ValidationNotNullViolation,
            `Replace requires a value for non-nullable property '${column.exposedName}'.`,
          );
        }
        // non-nullable WITH default: omit → database default applies
      }
    }

    return { values, children };
  }
}

function findChildByNav(
  schema: SchemaSnapshot,
  parent: TableModel,
  navigation: string,
): TableModel | undefined {
  for (const candidate of schema.tables) {
    if (
      candidate.foreignKeys.some(
        (fk) => fk.refTable === parent.exposedName && fk.navToMany === navigation,
      )
    ) {
      return candidate;
    }
  }
  return undefined;
}

export function coerce(value: unknown, column: ColumnModel): unknown {
  if (value === null || value === undefined) {
    if (!column.nullable) {
      throw new BindError(
        ErrorCodes.ValidationNotNullViolation,
        `Property '${column.exposedName}' cannot be null.`,
      );
    }
    return null;
  }

  try {
    const result = coerceCore(value, column);

    if (
      column.allowedValues !== undefined &&
      column.allowedValues.length > 0 &&
      typeof result === "string" &&
      !column.allowedValues.includes(result)
    ) {
      throw new BindError(
        ErrorCodes.ValidationInvalidValue,
        `'${result}' is not an allowed value for '${column.exposedName}'.`,
      );
    }

    if (
      column.maxLength !== undefined &&
      typeof result === "string" &&
      result.length > column.maxLength
    ) {
      throw new BindError(
        ErrorCodes.ValidationValueTooLong,
        `Value for '${column.exposedName}' exceeds max length ${column.maxLength}.`,
      );
    }

    return result;
  } catch (err) {
    if (err instanceof BindError) throw err;
    throw new BindError(
      ErrorCodes.ValidationInvalidValue,
      `Value for '${column.exposedName}' is not a valid ${column.edmType}.`,
    );
  }
}

function requireNumber(value: unknown, column: ColumnModel): number {
  if (typeof value !== "number") {
    throw new BindError(
      ErrorCodes.ValidationInvalidValue,
      `Property '${column.exposedName}' must be a number (strict coercion, spec 05 §5.1).`,
    );
  }
  return value;
}

function requireString(value: unknown, column: ColumnModel): string {
  if (typeof value !== "string") {
    throw new BindError(
      ErrorCodes.ValidationInvalidValue,
      `Property '${column.exposedName}' must be a string.`,
    );
  }
  return value;
}

function coerceCore(value: unknown, column: ColumnModel): unknown {
  switch (column.edmType) {
    case "Edm.Int16":
      return Math.trunc(requireNumber(value, column));
    case "Edm.Int32":
      return Math.trunc(requireNumber(value, column));
    case "Edm.Int64":
      return Math.trunc(requireNumber(value, column));
    case "Edm.Decimal":
      return requireNumber(value, column);
    case "Edm.Double":
      return requireNumber(value, column);
    case "Edm.Single":
      return requireNumber(value, column);
    case "Edm.Boolean":
      if (typeof value !== "boolean") {
        throw new BindError(
          ErrorCodes.ValidationInvalidValue,
          `Property '${column.exposedName}' must be a boolean.`,
        );
      }
      return value;
    case "Edm.String":
      return requireString(value, column);
    case "Edm.Guid":
      return requireString(value, column); // validated as UUID format
    case "Edm.DateTimeOffset":
      return requireString(value, column);
    case "Edm.Date":
      return requireString(value, column);
    case "Edm.TimeOfDay":
      return requireString(value, column);
    case "Edm.Binary":
      return requireString(value, column); // base64
    case "Edm.Untyped":
      return value;
    default:
      return requireString(value, column); // fallback-typed columns accept strings
  }
}
