/**
 * Normalized, engine-agnostic schema snapshot (port of
 * src/EzOdata.Core/Schema/SchemaModel.cs, spec 04 §5). Single source of truth
 * for EDM/CSDL models, SQL compilation, docs, and MCP.
 */

export interface ColumnModel {
  readonly dbName: string;
  readonly exposedName: string;
  readonly dbType: string;
  /** EDM type per the total mapping of spec 04 §6, e.g. "Edm.Int32". */
  readonly edmType: string;
  readonly nullable: boolean;
  readonly maxLength?: number;
  readonly precision?: number;
  readonly scale?: number;
  readonly isPrimaryKey: boolean;
  readonly isAutoGenerated: boolean;
  readonly isComputed: boolean;
  readonly defaultExpression?: string;
  readonly comment?: string;
  /** Set when edmType is a fallback (unmapped db type exposed as Edm.String, spec 04 CON-8). */
  readonly isFallbackType: boolean;
  /** Enum/check-constraint values where the engine exposes them (spec 04 §6). */
  readonly allowedValues?: readonly string[];
}

export interface ForeignKeyModel {
  readonly name: string;
  readonly columns: readonly string[];
  readonly refTable: string;
  readonly refColumns: readonly string[];
  /** Navigation property name on the child pointing at the parent (spec 04 §5.3). */
  readonly navToOne: string;
  /** Navigation property name on the parent pointing at children. */
  readonly navToMany: string;
}

export interface TableModel {
  readonly dbSchema: string;
  readonly dbName: string;
  readonly exposedName: string;
  readonly isView: boolean;
  readonly writable: boolean;
  readonly comment?: string;
  readonly columns: readonly ColumnModel[];
  readonly primaryKey: readonly string[];
  readonly uniqueConstraints: readonly (readonly string[])[];
  readonly foreignKeys: readonly ForeignKeyModel[];
}

export interface SchemaSnapshot {
  readonly version: number;
  readonly engine: string;
  readonly collectedAt: string;
  readonly tables: readonly TableModel[];
}

export function hasKey(table: TableModel): boolean {
  return table.primaryKey.length > 0;
}

export function tableCount(snapshot: SchemaSnapshot): number {
  return snapshot.tables.filter((t) => !t.isView).length;
}

export function viewCount(snapshot: SchemaSnapshot): number {
  return snapshot.tables.filter((t) => t.isView).length;
}

export function findTable(snapshot: SchemaSnapshot, exposedName: string): TableModel | undefined {
  return snapshot.tables.find((t) => t.exposedName === exposedName);
}

export function findColumn(table: TableModel, exposedName: string): ColumnModel | undefined {
  return table.columns.find((c) => c.exposedName === exposedName);
}
