/**
 * REST handler unit tests.
 */

import { describe, expect, it, vi } from "vitest";
import { RestHandler, type RestHandlerConfig, type RestRequest } from "../../../src/rest/handler.js";
import { PolicyEngine } from "../../../src/core/policy/engine.js";
import { DEV_BYPASS_IDENTITY } from "../../../src/core/policy/model.js";
import type { ServiceRuntime, QueryExecutor, WriteExecutor } from "../../../src/connectors/contracts.js";
import { Row } from "../../../src/core/result.js";
import { DEFAULT_SERVICE_OPTIONS } from "../../../src/core/services.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";

const SCHEMA: SchemaSnapshot = {
  version: 1,
  engine: "postgresql",
  collectedAt: "2026-01-01T00:00:00Z",
  tables: [
    {
      dbSchema: "public",
      dbName: "products",
      exposedName: "products",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "name", exposedName: "name", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "price", exposedName: "price", dbType: "numeric", edmType: "Edm.Decimal", nullable: true, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
  ],
};

const RUNTIME: ServiceRuntime = {
  name: "test",
  connectorType: "postgresql",
  connection: { tls: { mode: "disable", allowInvalid: false }, extra: {} },
  schema: SCHEMA,
  options: DEFAULT_SERVICE_OPTIONS,
  schemaVersion: "1",
  status: "active",
};

function makeRow(fields: Record<string, unknown>): Row {
  const r = new Row();
  for (const [k, v] of Object.entries(fields)) r.set(k, v);
  return r;
}

function makeQueryExecutor(rows: Row[] = [], hasMore = false): QueryExecutor {
  return {
    query: vi.fn().mockResolvedValue({ rows, hasMore }),
    count: vi.fn().mockResolvedValue(rows.length),
  };
}

function makeWriteExecutor(affectedCount = 1, rows: Row[] = []): WriteExecutor {
  return {
    write: vi.fn().mockResolvedValue({ affectedCount, records: rows }),
    writeAtomic: vi.fn().mockResolvedValue([{ affectedCount, records: rows }]),
  };
}

function makeConfig(queryExec?: QueryExecutor, writeExec?: WriteExecutor): RestHandlerConfig {
  return {
    resolveRuntime: async (name) => (name === "test" ? RUNTIME : undefined),
    getQueryExecutor: () => queryExec ?? makeQueryExecutor(),
    getWriteExecutor: () => writeExec,
    policyEngine: new PolicyEngine(),
    resolveRoleRules: async () => [],
    rowFilterParser: () => { throw new Error("no row filters in test"); },
  };
}

function makeReq(method: string, path: string, opts: Partial<RestRequest> = {}): RestRequest {
  return {
    method,
    path,
    queryString: "",
    identity: DEV_BYPASS_IDENTITY,
    headers: {},
    ...opts,
  };
}

describe("RestHandler", () => {
  describe("_table listing", () => {
    it("returns table list", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("test", makeReq("GET", "_table"));
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body);
      expect(body.resource).toHaveLength(1);
      expect(body.resource[0].name).toBe("products");
    });

    it("returns 405 for non-GET on _table listing", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("test", makeReq("POST", "_table"));
      expect(resp.status).toBe(405);
    });
  });

  describe("table schema", () => {
    it("returns column descriptions", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("test", makeReq("GET", "_table/products/_schema"));
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body);
      expect(body.name).toBe("products");
      expect(body.fields).toHaveLength(3);
    });
  });

  describe("query collection", () => {
    it("returns rows", async () => {
      const rows = [makeRow({ id: 1, name: "Widget", price: 9.99 })];
      const handler = new RestHandler(makeConfig(makeQueryExecutor(rows)));
      const resp = await handler.handleForService("test", makeReq("GET", "_table/products"));
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body);
      expect(body.resource).toHaveLength(1);
      expect(body.resource[0].name).toBe("Widget");
    });

    it("applies filter from querystring", async () => {
      const exec = makeQueryExecutor([]);
      const handler = new RestHandler(makeConfig(exec));
      await handler.handleForService("test", makeReq("GET", "_table/products", { queryString: "filter=price > 10" }));
      const queryCall = (exec.query as ReturnType<typeof vi.fn>).mock.calls[0]![0];
      expect(queryCall.query.filter).toBeDefined();
    });

    it("returns 404 for unknown table", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("test", makeReq("GET", "_table/nonexistent"));
      expect(resp.status).toBe(404);
    });

    it("includes count when requested", async () => {
      const rows = [makeRow({ id: 1, name: "X" })];
      const exec = makeQueryExecutor(rows);
      const handler = new RestHandler(makeConfig(exec));
      await handler.handleForService("test", makeReq("GET", "_table/products", { queryString: "include_count=true" }));
      expect((exec.count as ReturnType<typeof vi.fn>)).toHaveBeenCalled();
    });
  });

  describe("get by id", () => {
    it("returns single row", async () => {
      const rows = [makeRow({ id: 1, name: "Widget" })];
      const handler = new RestHandler(makeConfig(makeQueryExecutor(rows)));
      const resp = await handler.handleForService("test", makeReq("GET", "_table/products/1"));
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body);
      expect(body.id).toBe(1);
    });

    it("returns 404 when not found", async () => {
      const handler = new RestHandler(makeConfig(makeQueryExecutor([])));
      const resp = await handler.handleForService("test", makeReq("GET", "_table/products/999"));
      expect(resp.status).toBe(404);
    });
  });

  describe("insert", () => {
    it("returns 201 with created row", async () => {
      const rows = [makeRow({ id: 1, name: "Widget" })];
      const writeExec = makeWriteExecutor(1, rows);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("POST", "_table/products", { body: { name: "Widget" } }));
      expect(resp.status).toBe(201);
    });

    it("returns 403 when no write executor", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("test", makeReq("POST", "_table/products", { body: { name: "Widget" } }));
      expect(resp.status).toBe(403);
    });
  });

  describe("update by id", () => {
    it("returns 200 on PATCH", async () => {
      const rows = [makeRow({ id: 1, name: "Updated" })];
      const writeExec = makeWriteExecutor(1, rows);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("PATCH", "_table/products/1", { body: { name: "Updated" } }));
      expect(resp.status).toBe(200);
    });

    it("returns 404 when row not found", async () => {
      const writeExec = makeWriteExecutor(0, []);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("PATCH", "_table/products/999", { body: { name: "X" } }));
      expect(resp.status).toBe(404);
    });
  });

  describe("delete by id", () => {
    it("returns 204 on success", async () => {
      const writeExec = makeWriteExecutor(1);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("DELETE", "_table/products/1"));
      expect(resp.status).toBe(204);
    });

    it("returns 404 when not found", async () => {
      const writeExec = makeWriteExecutor(0);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("DELETE", "_table/products/999"));
      expect(resp.status).toBe(404);
    });
  });

  describe("bulk delete", () => {
    it("deletes by ids=", async () => {
      const writeExec = makeWriteExecutor(2);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService(
        "test",
        makeReq("DELETE", "_table/products", { queryString: "ids=1,2" }),
      );
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body);
      expect(body.meta.affected).toBe(2);
    });

    it("returns 400 without ids= or filter=", async () => {
      const writeExec = makeWriteExecutor(0);
      const handler = new RestHandler(makeConfig(undefined, writeExec));
      const resp = await handler.handleForService("test", makeReq("DELETE", "_table/products"));
      expect(resp.status).toBe(400);
    });
  });

  describe("unknown service", () => {
    it("returns 404", async () => {
      const handler = new RestHandler(makeConfig());
      const resp = await handler.handleForService("unknown", makeReq("GET", "_table"));
      expect(resp.status).toBe(404);
    });
  });
});
