import { describe, expect, it } from "vitest";
import { buildCsdlXmlFull } from "../../../src/odata/csdl.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";

const SNAPSHOT: SchemaSnapshot = {
  version: 1,
  engine: "postgresql",
  collectedAt: "2026-01-01T00:00:00Z",
  tables: [
    {
      dbSchema: "public",
      dbName: "customers",
      exposedName: "customers",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "name", exposedName: "name", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "email", exposedName: "email", dbType: "varchar", edmType: "Edm.String", nullable: false, maxLength: 320, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "created_at", exposedName: "created_at", dbType: "timestamptz", edmType: "Edm.DateTimeOffset", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
    {
      dbSchema: "public",
      dbName: "orders",
      exposedName: "orders",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "bigserial", edmType: "Edm.Int64", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "customer_id", exposedName: "customer_id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "total", exposedName: "total", dbType: "numeric", edmType: "Edm.Decimal", nullable: false, precision: 12, scale: 2, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [
        {
          name: "orders_customer_id_fkey",
          columns: ["customer_id"],
          refTable: "customers",
          refColumns: ["id"],
          navToOne: "customer",
          navToMany: "orders",
        },
      ],
    },
  ],
};

describe("CSDL XML emitter", () => {
  it("produces valid XML header", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('<?xml version="1.0" encoding="utf-8"?>');
    expect(xml).toContain("edmx:Edmx");
    expect(xml).toContain('Version="4.0"');
  });

  it("includes EntityType names", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('EntityType Name="customers"');
    expect(xml).toContain('EntityType Name="orders"');
  });

  it("includes Key and PropertyRef for primary key", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain("<Key>");
    expect(xml).toContain('<PropertyRef Name="id"');
  });

  it("includes properties with EDM types", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('Property Name="id"');
    expect(xml).toContain("Edm.Int32");
    expect(xml).toContain("Edm.DateTimeOffset");
    expect(xml).toContain("Edm.Decimal");
  });

  it("includes MaxLength for varchar columns", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('MaxLength="320"');
  });

  it("includes Precision and Scale for decimal columns", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('Precision="12"');
    expect(xml).toContain('Scale="2"');
  });

  it("includes to-one navigation property 'customer'", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('NavigationProperty Name="customer"');
  });

  it("includes to-many navigation property 'orders'", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('NavigationProperty Name="orders"');
  });

  it("includes EntityContainer", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain("EntityContainer");
    expect(xml).toContain('EntitySet Name="customers"');
    expect(xml).toContain('EntitySet Name="orders"');
  });

  it("includes navigation property bindings", () => {
    const xml = buildCsdlXmlFull("sales", SNAPSHOT);
    expect(xml).toContain('NavigationPropertyBinding Path="customer"');
    expect(xml).toContain('NavigationPropertyBinding Path="orders"');
  });

  it("view without primary key has no Key element", () => {
    const snapshot: SchemaSnapshot = {
      ...SNAPSHOT,
      tables: [
        {
          dbSchema: "public",
          dbName: "v_totals",
          exposedName: "v_totals",
          isView: true,
          writable: false,
          columns: [
            { dbName: "customer_id", exposedName: "customer_id", dbType: "int4", edmType: "Edm.Int32", nullable: true, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
          ],
          primaryKey: [],
          uniqueConstraints: [],
          foreignKeys: [],
        },
      ],
    };
    const xml = buildCsdlXmlFull("sales", snapshot);
    expect(xml).not.toContain("<Key>");
    expect(xml).toContain('EntityType Name="v_totals"');
  });

  it("sanitizes service name with special chars", () => {
    const xml = buildCsdlXmlFull("my-service", SNAPSHOT);
    expect(xml).toContain("EzOdata.my_service");
  });
});
