import { describe, expect, it, vi } from "vitest";
import { ODataHandler, type ODataHandlerConfig, type ODataRequest } from "../../../src/odata/handler.js";
import { SkipTokenCodec } from "../../../src/odata/skiptoken.js";
import { PolicyEngine } from "../../../src/core/policy/engine.js";
import { DEV_BYPASS_IDENTITY } from "../../../src/core/policy/model.js";
import type { ServiceRuntime, QueryExecutor } from "../../../src/connectors/contracts.js";
import { Row } from "../../../src/core/result.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";
import { DEFAULT_SERVICE_OPTIONS } from "../../../src/core/services.js";

// ---- Minimal schema fixture ----
const SCHEMA: SchemaSnapshot = {
  version: 1,
  engine: "postgresql",
  collectedAt: "2026-01-01T00:00:00Z",
  tables: [
    {
      dbSchema: "public",
      dbName: "customers",
      exposedName: "customers",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "name", exposedName: "name", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "email", exposedName: "email", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
  ],
};

const RUNTIME: ServiceRuntime = {
  name: "test",
  connectorType: "postgresql",
  connection: { tls: { mode: "disable", allowInvalid: false }, extra: {} },
  schema: SCHEMA,
  options: DEFAULT_SERVICE_OPTIONS,
  schemaVersion: "1",
  status: "active",
};

function makeRow(fields: Record<string, unknown>): Row {
  const r = new Row();
  for (const [k, v] of Object.entries(fields)) r.set(k, v);
  return r;
}

function makeExecutor(rows: Row[], hasMore = false): QueryExecutor {
  return {
    query: vi.fn().mockResolvedValue({ rows, hasMore }),
    count: vi.fn().mockResolvedValue(rows.length),
  };
}

function makeConfig(executor: QueryExecutor): ODataHandlerConfig {
  return {
    resolveRuntime: async (name) => (name === "test" ? RUNTIME : undefined),
    getExecutor: () => executor,
    skipTokenCodec: new SkipTokenCodec(Buffer.from("test-signing-key-32-bytes-exactly!!")),
    policyEngine: new PolicyEngine(),
    resolveRoleRules: async () => [],
    rowFilterParser: () => { throw new Error("no row filters in test"); },
  };
}

function makeReq(path: string, qs = ""): ODataRequest {
  return {
    method: "GET",
    path,
    queryString: qs,
    serviceRoot: "http://localhost/api/odata/test",
    identity: DEV_BYPASS_IDENTITY,
    headers: {},
  };
}

describe("ODataHandler", () => {
  it("returns 404 for unknown service", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("ghost", makeReq("customers"));
    expect(res.status).toBe(404);
  });

  it("returns 503 when service is disabled", async () => {
    const config = makeConfig(makeExecutor([]));
    config.resolveRuntime = async () => ({ ...RUNTIME, status: "disabled" as const });
    const handler = new ODataHandler(config);
    const res = await handler.handleForService("test", makeReq("customers"));
    expect(res.status).toBe(503);
  });

  it("service document lists entity sets", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq(""));
    expect(res.status).toBe(200);
    const body = JSON.parse(res.body as string) as { value: Array<{ name: string }> };
    expect(body.value.some((v) => v.name === "customers")).toBe(true);
  });

  it("$metadata returns XML", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("$metadata"));
    expect(res.status).toBe(200);
    expect(res.contentType).toContain("xml");
    expect(res.body as string).toContain('EntityType Name="customers"');
  });

  it("collection returns rows wrapped in value array", async () => {
    const rows = [makeRow({ id: 1, name: "Acme", email: "a@a.com" })];
    const handler = new ODataHandler(makeConfig(makeExecutor(rows)));
    const res = await handler.handleForService("test", makeReq("customers"));
    expect(res.status).toBe(200);
    const body = JSON.parse(res.body as string) as { value: Array<{ id: number }> };
    expect(body.value[0]?.id).toBe(1);
  });

  it("$top limits returned rows", async () => {
    const rows = [makeRow({ id: 1, name: "A", email: "a@a.com" }), makeRow({ id: 2, name: "B", email: "b@b.com" })];
    const handler = new ODataHandler(makeConfig(makeExecutor(rows)));
    const res = await handler.handleForService("test", makeReq("customers", "$top=1"));
    expect(res.status).toBe(200);
  });

  it("nextLink present when hasMore=true", async () => {
    const rows = Array.from({ length: 5 }, (_, i) => makeRow({ id: i + 1, name: `C${i}`, email: `c${i}@c.com` }));
    const executor: QueryExecutor = {
      query: vi.fn().mockResolvedValue({ rows, hasMore: true }),
      count: vi.fn().mockResolvedValue(10),
    };
    const handler = new ODataHandler(makeConfig(executor));
    const res = await handler.handleForService("test", makeReq("customers", "$top=5"));
    const body = JSON.parse(res.body as string) as { "@odata.nextLink"?: string };
    expect(body["@odata.nextLink"]).toBeDefined();
  });

  it("by-key returns single entity", async () => {
    const rows = [makeRow({ id: 1, name: "Acme", email: "a@a.com" })];
    const handler = new ODataHandler(makeConfig(makeExecutor(rows)));
    const res = await handler.handleForService("test", makeReq("customers(1)"));
    expect(res.status).toBe(200);
    const body = JSON.parse(res.body as string) as { id: number };
    expect(body.id).toBe(1);
  });

  it("by-key returns 404 when not found", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("customers(99)"));
    expect(res.status).toBe(404);
  });

  it("unknown entity set returns 404", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("unicorns"));
    expect(res.status).toBe(404);
  });

  it("malformed filter returns 400", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("customers", "$filter=name eq"));
    expect(res.status).toBe(400);
    const body = JSON.parse(res.body as string) as { error: { code: string; message: string } };
    expect(body.error.code).toBeDefined();
    expect(body.error.message).toBeDefined();
  });

  it("invalid skiptoken returns 400", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("customers", "$skiptoken=tampered"));
    expect(res.status).toBe(400);
  });

  it("$count=true includes @odata.count", async () => {
    const rows = [makeRow({ id: 1, name: "A", email: "a@a.com" })];
    const executor: QueryExecutor = {
      query: vi.fn().mockResolvedValue({ rows, hasMore: false }),
      count: vi.fn().mockResolvedValue(8),
    };
    const handler = new ODataHandler(makeConfig(executor));
    const res = await handler.handleForService("test", makeReq("customers", "$count=true"));
    const body = JSON.parse(res.body as string) as { "@odata.count"?: number };
    expect(body["@odata.count"]).toBe(8);
  });

  it("$count path segment returns plain text number", async () => {
    const executor: QueryExecutor = {
      query: vi.fn().mockResolvedValue({ rows: [], hasMore: false }),
      count: vi.fn().mockResolvedValue(8),
    };
    const handler = new ODataHandler(makeConfig(executor));
    const res = await handler.handleForService("test", makeReq("customers/$count"));
    expect(res.status).toBe(200);
    expect(res.body).toBe("8");
  });

  it("response always has OData-Version header", async () => {
    const handler = new ODataHandler(makeConfig(makeExecutor([])));
    const res = await handler.handleForService("test", makeReq("customers"));
    expect(res.headers["OData-Version"]).toBe("4.0");
  });
});
