/**
 * OData write handler unit tests (port of WriteConformanceTests.cs, spec 05 §5–7).
 * Uses stub executors — no database required.
 */

import { describe, expect, it, vi } from "vitest";
import { ODataWriteHandler, type ODataWriteHandlerConfig, type ODataWriteRequest } from "../../../src/odata/write-handler.js";
import { PolicyEngine } from "../../../src/core/policy/engine.js";
import { DEV_BYPASS_IDENTITY } from "../../../src/core/policy/model.js";
import type { ServiceRuntime, WriteExecutor, QueryExecutor } from "../../../src/connectors/contracts.js";
import { Row } from "../../../src/core/result.js";
import { DEFAULT_SERVICE_OPTIONS } from "../../../src/core/services.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";

const SCHEMA: SchemaSnapshot = {
  version: 1,
  engine: "postgresql",
  collectedAt: "2026-01-01T00:00:00Z",
  tables: [
    {
      dbSchema: "public",
      dbName: "customers",
      exposedName: "customers",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "name", exposedName: "name", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "email", exposedName: "email", dbType: "text", edmType: "Edm.String", nullable: true, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
    {
      dbSchema: "public",
      dbName: "views_only",
      exposedName: "views_only",
      isView: true,
      writable: false,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
  ],
};

const RUNTIME: ServiceRuntime = {
  name: "test",
  connectorType: "postgresql",
  connection: { tls: { mode: "disable", allowInvalid: false }, extra: {} },
  schema: SCHEMA,
  options: DEFAULT_SERVICE_OPTIONS,
  schemaVersion: "1",
  status: "active",
};

function makeRow(fields: Record<string, unknown>): Row {
  const r = new Row();
  for (const [k, v] of Object.entries(fields)) r.set(k, v);
  return r;
}

function makeWriteExecutor(affectedCount = 1, returnedRows?: Row[]): WriteExecutor {
  const rows = returnedRows ?? [];
  return {
    write: vi.fn().mockResolvedValue({ affectedCount, records: rows, errorCode: undefined }),
    writeAtomic: vi.fn().mockResolvedValue([{ affectedCount, records: rows }]),
  };
}

function makeQueryExecutor(rows: Row[] = []): QueryExecutor {
  return {
    query: vi.fn().mockResolvedValue({ rows, hasMore: false }),
    count: vi.fn().mockResolvedValue(rows.length),
  };
}

function makeConfig(writeExecutor?: WriteExecutor, queryExecutor?: QueryExecutor): ODataWriteHandlerConfig {
  return {
    resolveRuntime: async (name) => (name === "test" ? RUNTIME : undefined),
    getWriteExecutor: (_runtime) => writeExecutor,
    getQueryExecutor: (_runtime) => queryExecutor ?? makeQueryExecutor(),
    policyEngine: new PolicyEngine(),
    resolveRoleRules: async () => [],
    rowFilterParser: () => { throw new Error("no row filters in test"); },
  };
}

function makeReq(method: string, path: string, body?: unknown): ODataWriteRequest {
  return {
    method,
    path,
    queryString: "",
    serviceRoot: "http://localhost/api/odata/test",
    identity: DEV_BYPASS_IDENTITY,
    headers: {},
    body,
  };
}

describe("ODataWriteHandler", () => {
  describe("unknown service", () => {
    it("returns 404 for unknown service", async () => {
      const handler = new ODataWriteHandler(makeConfig());
      const resp = await handler.handleForService("unknown", makeReq("POST", "customers", { name: "Alice" }));
      expect(resp.status).toBe(404);
    });
  });

  describe("read-only service", () => {
    it("returns 403 when write executor is absent", async () => {
      const handler = new ODataWriteHandler(makeConfig(undefined));
      const resp = await handler.handleForService("test", makeReq("POST", "customers", { name: "Alice" }));
      expect(resp.status).toBe(403);
    });
  });

  describe("POST (insert)", () => {
    it("returns 201 with location header for single insert", async () => {
      const returnedRow = makeRow({ id: 42, name: "Alice", email: null });
      const executor = makeWriteExecutor(1, [returnedRow]);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const resp = await handler.handleForService("test", makeReq("POST", "customers", { name: "Alice" }));

      expect(resp.status).toBe(201);
      expect(resp.headers["Location"]).toContain("customers(42)");
      const body = JSON.parse(resp.body as string);
      expect(body["name"]).toBe("Alice");
      expect(body["@odata.context"]).toContain("$metadata#customers");
    });

    it("returns 204 for prefer:return=minimal", async () => {
      const executor = makeWriteExecutor(1, []);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const resp = await handler.handleForService("test", {
        ...makeReq("POST", "customers", { name: "Alice" }),
        headers: { prefer: "return=minimal" },
      });

      expect(resp.status).toBe(204);
    });

    it("returns 400 when body is missing", async () => {
      const executor = makeWriteExecutor();
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("POST", "customers", null));
      expect(resp.status).toBe(400);
    });

    it("returns 400 for unknown property", async () => {
      const executor = makeWriteExecutor();
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("POST", "customers", { name: "Alice", bogus: 1 }));
      expect(resp.status).toBe(400);
      const body = JSON.parse(resp.body as string);
      expect(body.error.message).toContain("bogus");
    });

    it("returns 400 for autoGenerated column", async () => {
      const executor = makeWriteExecutor();
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("POST", "customers", { id: 1, name: "Alice" }));
      expect(resp.status).toBe(400);
    });

    it("returns 403 for view entity set", async () => {
      const executor = makeWriteExecutor();
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("POST", "views_only", { id: 1 }));
      expect(resp.status).toBe(403);
    });

    it("returns 200 for bulk insert array", async () => {
      const rows = [makeRow({ id: 1, name: "Alice" }), makeRow({ id: 2, name: "Bob" })];
      const executor = makeWriteExecutor(2, rows);
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("POST", "customers", [
        { name: "Alice" },
        { name: "Bob" },
      ]));
      expect(resp.status).toBe(201);
      const body = JSON.parse(resp.body as string);
      expect(body.value).toHaveLength(2);
    });
  });

  describe("PATCH (update)", () => {
    it("returns 200 with updated row", async () => {
      const updatedRow = makeRow({ id: 1, name: "Updated", email: null });
      const executor = makeWriteExecutor(1, [updatedRow]);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const resp = await handler.handleForService("test", makeReq("PATCH", "customers(1)", { name: "Updated" }));

      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body as string);
      expect(body["name"]).toBe("Updated");
    });

    it("returns 404 when row not found", async () => {
      const executor = makeWriteExecutor(0, []);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const resp = await handler.handleForService("test", makeReq("PATCH", "customers(999)", { name: "X" }));
      expect(resp.status).toBe(404);
    });

    it("returns 400 for key mismatch in body", async () => {
      const executor = makeWriteExecutor(1, []);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const resp = await handler.handleForService("test", makeReq("PATCH", "customers(1)", { id: 2, name: "X" }));
      expect(resp.status).toBe(400);
    });
  });

  describe("DELETE", () => {
    it("returns 204 on success", async () => {
      const executor = makeWriteExecutor(1);
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("DELETE", "customers(1)"));
      expect(resp.status).toBe(204);
    });

    it("returns 404 when row not found", async () => {
      const executor = makeWriteExecutor(0);
      const handler = new ODataWriteHandler(makeConfig(executor));
      const resp = await handler.handleForService("test", makeReq("DELETE", "customers(999)"));
      expect(resp.status).toBe(404);
    });
  });

  describe("$batch", () => {
    it("dispatches sub-requests and returns batch response", async () => {
      const rows = [makeRow({ id: 1, name: "Alice" })];
      const executor = makeWriteExecutor(1, rows);
      const handler = new ODataWriteHandler(makeConfig(executor));

      const batch = {
        requests: [
          { id: "r1", method: "POST", url: "customers", body: { name: "Alice" } },
          { id: "r2", method: "DELETE", url: "customers(1)" },
        ],
      };

      const resp = await handler.handleForService("test", makeReq("POST", "$batch", batch));
      expect(resp.status).toBe(200);
      const body = JSON.parse(resp.body as string);
      expect(body.responses).toHaveLength(2);
      expect(body.responses[0].id).toBe("r1");
    });

    it("returns 400 for batch > 100 requests", async () => {
      const executor = makeWriteExecutor(1);
      const handler = new ODataWriteHandler(makeConfig(executor));
      const requests = Array.from({ length: 101 }, (_, i) => ({
        id: `r${i}`,
        method: "DELETE",
        url: `customers(${i})`,
      }));
      const resp = await handler.handleForService("test", makeReq("POST", "$batch", { requests }));
      expect(resp.status).toBe(400);
    });
  });

  describe("ETag concurrency", () => {
    it("requires If-Match when concurrency column configured", async () => {
      const executor = makeWriteExecutor(1);
      // Use a schema that has a "version" column so concurrency check fires
      const schemaWithVersion = {
        ...SCHEMA,
        tables: [{
          ...SCHEMA.tables[0]!,
          columns: [
            ...SCHEMA.tables[0]!.columns,
            { dbName: "version", exposedName: "version", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
          ],
        }, ...SCHEMA.tables.slice(1)],
      };
      const runtimeWithConcurrency: ServiceRuntime = {
        ...RUNTIME,
        schema: schemaWithVersion,
        options: { ...DEFAULT_SERVICE_OPTIONS, concurrencyColumns: ["version"] },
      };
      const config: ODataWriteHandlerConfig = {
        resolveRuntime: async (name) => (name === "test" ? runtimeWithConcurrency : undefined),
        getWriteExecutor: () => executor,
        getQueryExecutor: () => makeQueryExecutor(),
        policyEngine: new PolicyEngine(),
        resolveRoleRules: async () => [],
        rowFilterParser: () => { throw new Error("no row filters"); },
      };
      const handler = new ODataWriteHandler(config);
      const resp = await handler.handleForService("test", makeReq("PATCH", "customers(1)", { name: "X" }));
      expect(resp.status).toBe(428);
    });
  });
});
