using System.Data;
using EzOdata.Connectors.Abstractions;
using EzOdata.Core.Schema;
using Npgsql;

namespace EzOdata.Connectors.PostgreSql;

/// <summary>
/// Schema discovery via information_schema + pg_catalog (spec 04 §4).
/// FK column resolution uses pg_constraint/pg_attribute because
/// information_schema cannot order composite FK columns reliably.
/// </summary>
public sealed class PostgreSqlIntrospector : ISchemaIntrospector
{
    public async Task<SchemaSnapshot> IntrospectAsync(ConnectionSpec spec, IntrospectionOptions options, CancellationToken ct)
    {
        var connectionString = PostgreSqlConnectionStrings.Build(spec, connectTimeoutSeconds: 15);
        using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync(ct);

        var rawTables = await LoadTablesAsync(connection, ct);
        var rawColumns = await LoadColumnsAsync(connection, ct);
        var keyConstraints = await LoadKeyConstraintsAsync(connection, ct);
        var foreignKeys = await LoadForeignKeysAsync(connection, ct);

        // Apply include/exclude filters BEFORE building the snapshot — excluded objects
        // never exist as far as the platform is concerned (spec 04 §4 rule 1).
        var included = rawTables
            .Where(t => options.IncludeSchemas.Count == 0 || Core.Text.Glob.MatchesAny(t.Schema, options.IncludeSchemas))
            .Where(t => options.ExcludeTables.Count == 0 || !Core.Text.Glob.MatchesAny(t.Name, options.ExcludeTables))
            .Where(t => options.IncludeViews || !t.IsView)
            .ToList();

        var includedKeys = new HashSet<(string, string)>(included.Select(t => (t.Schema, t.Name)));

        var tables = new List<TableModel>();
        foreach (var raw in included)
        {
            var columns = rawColumns
                .Where(c => c.Schema == raw.Schema && c.Table == raw.Name)
                .OrderBy(c => c.Ordinal)
                .ToList();

            var primaryKey = keyConstraints
                .Where(k => k.Schema == raw.Schema && k.Table == raw.Name && k.IsPrimary)
                .OrderBy(k => k.Ordinal)
                .Select(k => Expose(k.Column, options))
                .ToList();

            var uniques = keyConstraints
                .Where(k => k.Schema == raw.Schema && k.Table == raw.Name && !k.IsPrimary)
                .GroupBy(k => k.ConstraintName)
                .Select(g => (IReadOnlyList<string>)g.OrderBy(k => k.Ordinal).Select(k => Expose(k.Column, options)).ToList())
                .ToList();

            var pkSet = new HashSet<string>(primaryKey, StringComparer.Ordinal);
            var columnModels = columns.Select(c =>
            {
                var (edmType, fallback) = PostgreSqlTypeMap.Map(c.UdtName);
                var exposed = Expose(c.Name, options);
                return new ColumnModel
                {
                    DbName = c.Name,
                    ExposedName = exposed,
                    DbType = c.UdtName,
                    EdmType = edmType,
                    IsFallbackType = fallback,
                    Nullable = c.Nullable && !pkSet.Contains(exposed),
                    MaxLength = c.MaxLength,
                    Precision = c.Precision,
                    Scale = c.Scale,
                    IsPrimaryKey = pkSet.Contains(exposed),
                    IsAutoGenerated = c.IsIdentity || (c.Default?.StartsWith("nextval(", StringComparison.Ordinal) ?? false),
                    IsComputed = c.IsGenerated,
                    DefaultExpression = c.Default,
                    Comment = c.Comment,
                };
            }).ToList();

            tables.Add(new TableModel
            {
                DbSchema = raw.Schema,
                DbName = raw.Name,
                ExposedName = Expose(raw.Name, options),
                IsView = raw.IsView,
                Writable = !raw.IsView, // v1: all views read-only (spec 04 §4 rule 2)
                Comment = raw.Comment,
                Columns = columnModels,
                PrimaryKey = primaryKey,
                UniqueConstraints = uniques,
            });
        }

        AttachForeignKeys(tables, foreignKeys, includedKeys, options);

        return new SchemaSnapshot
        {
            Engine = "postgresql",
            CollectedAt = DateTimeOffset.UtcNow,
            Tables = tables.OrderBy(t => t.ExposedName, StringComparer.Ordinal).ToList(),
        };
    }

    private static void AttachForeignKeys(
        List<TableModel> tables, List<RawForeignKey> foreignKeys,
        HashSet<(string, string)> includedKeys, IntrospectionOptions options)
    {
        // Names must dedupe within each owning type: to-one names share the column namespace
        // on the child; to-many names share it on the parent (spec 04 §5.3).
        var childTaken = tables.ToDictionary(
            t => (t.DbSchema, t.DbName),
            t => new HashSet<string>(t.Columns.Select(c => c.ExposedName), StringComparer.Ordinal));
        var parentTaken = tables.ToDictionary(
            t => (t.DbSchema, t.DbName),
            t => new HashSet<string>(t.Columns.Select(c => c.ExposedName), StringComparer.Ordinal));

        var fkModels = tables.ToDictionary(t => (t.DbSchema, t.DbName), _ => new List<ForeignKeyModel>());

        foreach (var fk in foreignKeys.OrderBy(f => f.Name, StringComparer.Ordinal))
        {
            // FKs touching excluded tables vanish with them.
            if (!includedKeys.Contains((fk.Schema, fk.Table)) || !includedKeys.Contains((fk.RefSchema, fk.RefTable)))
            {
                continue;
            }

            var child = tables.First(t => t.DbSchema == fk.Schema && t.DbName == fk.Table);
            var parent = tables.First(t => t.DbSchema == fk.RefSchema && t.DbName == fk.RefTable);

            var navToOne = NavigationNaming.ToOneName(
                fk.Columns, parent.ExposedName, fk.Name, childTaken[(child.DbSchema, child.DbName)]);
            var navToMany = NavigationNaming.ToManyName(
                child.ExposedName, fk.Name, parentTaken[(parent.DbSchema, parent.DbName)]);

            fkModels[(child.DbSchema, child.DbName)].Add(new ForeignKeyModel
            {
                Name = fk.Name,
                Columns = fk.Columns.Select(c => Expose(c, options)).ToList(),
                RefTable = parent.ExposedName,
                RefColumns = fk.RefColumns.Select(c => Expose(c, options)).ToList(),
                NavToOne = navToOne,
                NavToMany = navToMany,
            });
        }

        for (var i = 0; i < tables.Count; i++)
        {
            var key = (tables[i].DbSchema, tables[i].DbName);
            tables[i] = tables[i] with { ForeignKeys = fkModels[key] };
        }
    }

    private static string Expose(string dbName, IntrospectionOptions options) =>
        options.ExposedNameStyle == "pascal" ? ToPascal(dbName) : dbName;

    private static string ToPascal(string snake)
    {
        var parts = snake.Split(['_'], StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p.Substring(1)));
    }

    // ---- raw catalog queries ----

    private sealed record RawTable(string Schema, string Name, bool IsView, string? Comment);

    private sealed record RawColumn(
        string Schema, string Table, string Name, int Ordinal, string UdtName, bool Nullable,
        int? MaxLength, int? Precision, int? Scale, string? Default, bool IsIdentity, bool IsGenerated, string? Comment);

    private sealed record RawKeyColumn(string Schema, string Table, string ConstraintName, bool IsPrimary, string Column, int Ordinal);

    private sealed record RawForeignKey(
        string Name, string Schema, string Table, IReadOnlyList<string> Columns,
        string RefSchema, string RefTable, IReadOnlyList<string> RefColumns);

    private static async Task<List<RawTable>> LoadTablesAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        const string sql = """
            SELECT n.nspname, c.relname, c.relkind, obj_description(c.oid, 'pg_class')
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'p', 'v', 'm')
              AND n.nspname NOT IN ('pg_catalog', 'information_schema')
              AND n.nspname NOT LIKE 'pg_%'
            ORDER BY n.nspname, c.relname
            """;

        var result = new List<RawTable>();
        using var command = new NpgsqlCommand(sql, connection);
        using var reader = await command.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct))
        {
            var kind = reader.GetChar(2);
            result.Add(new RawTable(
                reader.GetString(0), reader.GetString(1),
                IsView: kind is 'v' or 'm',
                Comment: reader.IsDBNull(3) ? null : reader.GetString(3)));
        }

        return result;
    }

    private static async Task<List<RawColumn>> LoadColumnsAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        const string sql = """
            SELECT c.table_schema, c.table_name, c.column_name, c.ordinal_position, c.udt_name,
                   c.is_nullable = 'YES', c.character_maximum_length, c.numeric_precision, c.numeric_scale,
                   c.column_default, c.is_identity = 'YES', c.is_generated = 'ALWAYS',
                   col_description(format('%I.%I', c.table_schema, c.table_name)::regclass::oid, c.ordinal_position)
            FROM information_schema.columns c
            WHERE c.table_schema NOT IN ('pg_catalog', 'information_schema')
            ORDER BY c.table_schema, c.table_name, c.ordinal_position
            """;

        var result = new List<RawColumn>();
        using var command = new NpgsqlCommand(sql, connection);
        using var reader = await command.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct))
        {
            result.Add(new RawColumn(
                reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetInt32(3),
                reader.GetString(4), reader.GetBoolean(5),
                reader.IsDBNull(6) ? null : reader.GetInt32(6),
                reader.IsDBNull(7) ? null : reader.GetInt32(7),
                reader.IsDBNull(8) ? null : reader.GetInt32(8),
                reader.IsDBNull(9) ? null : reader.GetString(9),
                reader.GetBoolean(10), reader.GetBoolean(11),
                reader.IsDBNull(12) ? null : reader.GetString(12)));
        }

        return result;
    }

    private static async Task<List<RawKeyColumn>> LoadKeyConstraintsAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        const string sql = """
            SELECT tc.table_schema, tc.table_name, tc.constraint_name,
                   tc.constraint_type = 'PRIMARY KEY', kcu.column_name, kcu.ordinal_position
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON kcu.constraint_name = tc.constraint_name AND kcu.constraint_schema = tc.constraint_schema
            WHERE tc.constraint_type IN ('PRIMARY KEY', 'UNIQUE')
              AND tc.table_schema NOT IN ('pg_catalog', 'information_schema')
            ORDER BY tc.table_schema, tc.table_name, tc.constraint_name, kcu.ordinal_position
            """;

        var result = new List<RawKeyColumn>();
        using var command = new NpgsqlCommand(sql, connection);
        using var reader = await command.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct))
        {
            result.Add(new RawKeyColumn(
                reader.GetString(0), reader.GetString(1), reader.GetString(2),
                reader.GetBoolean(3), reader.GetString(4), reader.GetInt32(5)));
        }

        return result;
    }

    private static async Task<List<RawForeignKey>> LoadForeignKeysAsync(NpgsqlConnection connection, CancellationToken ct)
    {
        // pg_constraint keeps conkey/confkey ordered, which information_schema does not
        // guarantee for composite keys.
        const string sql = """
            SELECT con.conname,
                   srcns.nspname, src.relname,
                   tgtns.nspname, tgt.relname,
                   (SELECT array_agg(a.attname ORDER BY k.ord)
                      FROM unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord)
                      JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.attnum),
                   (SELECT array_agg(a.attname ORDER BY k.ord)
                      FROM unnest(con.confkey) WITH ORDINALITY AS k(attnum, ord)
                      JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.attnum)
            FROM pg_constraint con
            JOIN pg_class src ON src.oid = con.conrelid
            JOIN pg_namespace srcns ON srcns.oid = src.relnamespace
            JOIN pg_class tgt ON tgt.oid = con.confrelid
            JOIN pg_namespace tgtns ON tgtns.oid = tgt.relnamespace
            WHERE con.contype = 'f'
              AND srcns.nspname NOT IN ('pg_catalog', 'information_schema')
            ORDER BY con.conname
            """;

        var result = new List<RawForeignKey>();
        using var command = new NpgsqlCommand(sql, connection);
        using var reader = await command.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct))
        {
            result.Add(new RawForeignKey(
                Name: reader.GetString(0),
                Schema: reader.GetString(1),
                Table: reader.GetString(2),
                Columns: reader.GetFieldValue<string[]>(5),
                RefSchema: reader.GetString(3),
                RefTable: reader.GetString(4),
                RefColumns: reader.GetFieldValue<string[]>(6)));
        }

        return result;
    }
}
