using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using EzOdata.Core.Schema;

namespace EzOdata.Docs;

public enum ApiDialect { ODataV4, Rest }

/// <summary>
/// Generates OpenAPI 3.1 documents from a (trimmed) schema snapshot (spec 11 §2).
/// Read/write schemas differ; decimals are serialized as strings to avoid float loss;
/// masked fields are annotated and appear only in read schemas.
/// </summary>
public sealed class OpenApiGenerator
{
    public const string GeneratorVersion = "1.0";

    public string Generate(
        SchemaSnapshot schema, ApiDialect dialect, string serviceName, string serviceLabel,
        string schemaVersion, Uri serviceRoot)
    {
        var doc = new JsonObject
        {
            ["openapi"] = "3.1.0",
            ["info"] = new JsonObject
            {
                ["title"] = $"{serviceLabel} ({(dialect == ApiDialect.ODataV4 ? "OData v4" : "REST")})",
                ["version"] = "1.0",
                ["x-ez-schema-version"] = schemaVersion,
                ["x-ez-generator-version"] = GeneratorVersion,
            },
            ["servers"] = new JsonArray
            {
                new JsonObject { ["url"] = serviceRoot.ToString().TrimEnd('/') },
            },
            ["components"] = new JsonObject
            {
                ["securitySchemes"] = new JsonObject
                {
                    ["apiKey"] = new JsonObject { ["type"] = "apiKey", ["in"] = "header", ["name"] = "X-API-Key" },
                    ["bearer"] = new JsonObject { ["type"] = "http", ["scheme"] = "bearer" },
                },
                ["schemas"] = BuildSchemas(schema),
            },
            ["security"] = new JsonArray
            {
                new JsonObject { ["apiKey"] = new JsonArray() },
                new JsonObject { ["bearer"] = new JsonArray() },
            },
            ["paths"] = dialect == ApiDialect.ODataV4 ? BuildODataPaths(schema) : BuildRestPaths(schema),
        };

        return doc.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
    }

    public static string ComputeETag(string schemaVersion, string roleVersion, ApiDialect dialect)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes($"{schemaVersion}|{roleVersion}|{dialect}|{GeneratorVersion}"));
        var hex = new StringBuilder();
        for (var i = 0; i < 8; i++) hex.Append(bytes[i].ToString("x2"));
        return $"W/\"{hex}\"";
    }

    private static JsonObject BuildSchemas(SchemaSnapshot schema)
    {
        var schemas = new JsonObject();
        foreach (var table in schema.Tables)
        {
            schemas[table.ExposedName] = EntitySchema(table, writable: false);
            if (table.Writable)
            {
                schemas[$"{table.ExposedName}Create"] = EntitySchema(table, writable: true, forCreate: true);
                schemas[$"{table.ExposedName}Update"] = EntitySchema(table, writable: true, forCreate: false);
            }
        }

        return schemas;
    }

    private static JsonObject EntitySchema(TableModel table, bool writable, bool forCreate = false)
    {
        var properties = new JsonObject();
        var required = new JsonArray();

        foreach (var column in table.Columns)
        {
            if (writable && (column.IsAutoGenerated || column.IsComputed)) continue;

            properties[column.ExposedName] = PropertySchema(column);

            if (writable && !column.Nullable && column.DefaultExpression is null
                && (forCreate || !column.IsPrimaryKey))
            {
                required.Add(column.ExposedName);
            }
        }

        var schema = new JsonObject
        {
            ["type"] = "object",
            ["properties"] = properties,
        };
        if (required.Count > 0) schema["required"] = required;
        if (table.Comment is not null) schema["description"] = table.Comment;
        return schema;
    }

    private static JsonObject PropertySchema(ColumnModel column)
    {
        var schema = column.EdmType switch
        {
            "Edm.Int16" or "Edm.Int32" => Obj("integer", "int32"),
            "Edm.Int64" => Obj("integer", "int64"),
            "Edm.Decimal" => new JsonObject { ["type"] = "string", ["format"] = "decimal", ["x-ez-decimal"] = true },
            "Edm.Double" or "Edm.Single" => Obj("number", column.EdmType == "Edm.Single" ? "float" : "double"),
            "Edm.Boolean" => new JsonObject { ["type"] = "boolean" },
            "Edm.Guid" => Obj("string", "uuid"),
            "Edm.DateTimeOffset" => Obj("string", "date-time"),
            "Edm.Date" => Obj("string", "date"),
            "Edm.TimeOfDay" => Obj("string", "time"),
            "Edm.Binary" => Obj("string", "byte"),
            "Edm.Untyped" => new JsonObject(),
            _ when column.EdmType.StartsWith("Collection(", StringComparison.Ordinal) =>
                new JsonObject { ["type"] = "array", ["items"] = new JsonObject() },
            _ => new JsonObject { ["type"] = "string" },
        };

        if (column.Nullable) schema["nullable"] = true;
        if (column.MaxLength is { } max && schema["type"]?.GetValue<string>() == "string") schema["maxLength"] = max;
        if (column.AllowedValues is { Count: > 0 } allowed)
        {
            var enumArray = new JsonArray();
            foreach (var value in allowed) enumArray.Add(value);
            schema["enum"] = enumArray;
        }

        if (column.Comment is not null) schema["description"] = column.Comment;
        return schema;
    }

    private static JsonObject Obj(string type, string format) =>
        new() { ["type"] = type, ["format"] = format };

    private static JsonObject BuildODataPaths(SchemaSnapshot schema)
    {
        var paths = new JsonObject();
        foreach (var table in schema.Tables)
        {
            var set = table.ExposedName;
            var collection = new JsonObject
            {
                ["get"] = ODataListOperation(table),
            };
            if (table.Writable)
            {
                collection["post"] = ODataCreateOperation(table);
            }

            paths[$"/{set}"] = collection;

            if (table.HasKey)
            {
                var byKey = new JsonObject { ["get"] = ODataGetOperation(table) };
                if (table.Writable)
                {
                    byKey["patch"] = ODataUpdateOperation(table);
                    byKey["delete"] = DeleteOperation(table);
                }

                paths[$"/{set}({KeyTemplate(table)})"] = byKey;
            }
        }

        return paths;
    }

    private static JsonObject BuildRestPaths(SchemaSnapshot schema)
    {
        var paths = new JsonObject();
        foreach (var table in schema.Tables)
        {
            var set = table.ExposedName;
            var collection = new JsonObject { ["get"] = RestListOperation(table) };
            if (table.Writable) collection["post"] = ODataCreateOperation(table);
            paths[$"/_table/{set}"] = collection;

            if (table.HasKey)
            {
                var byKey = new JsonObject { ["get"] = ODataGetOperation(table) };
                if (table.Writable)
                {
                    byKey["patch"] = ODataUpdateOperation(table);
                    byKey["delete"] = DeleteOperation(table);
                }

                paths[$"/_table/{set}/{{id}}"] = byKey;
            }
        }

        return paths;
    }

    private static JsonObject ODataListOperation(TableModel table) => new()
    {
        ["summary"] = $"Query {table.ExposedName}",
        ["parameters"] = new JsonArray
        {
            QueryParam("$filter", "OData filter expression"),
            QueryParam("$select", "Comma-separated properties"),
            QueryParam("$orderby", "Sort expression"),
            QueryParam("$top", "Max rows", "integer"),
            QueryParam("$skip", "Rows to skip", "integer"),
            QueryParam("$count", "Include total count", "boolean"),
            QueryParam("$expand", "Related entities to include"),
        },
        ["responses"] = OkArrayResponse(table),
    };

    private static JsonObject RestListOperation(TableModel table) => new()
    {
        ["summary"] = $"Query {table.ExposedName}",
        ["parameters"] = new JsonArray
        {
            QueryParam("filter", "SQL-ish filter expression"),
            QueryParam("fields", "Comma-separated fields"),
            QueryParam("order", "Sort expression"),
            QueryParam("limit", "Max rows", "integer"),
            QueryParam("offset", "Rows to skip", "integer"),
            QueryParam("include_count", "Include total count", "boolean"),
        },
        ["responses"] = OkArrayResponse(table),
    };

    private static JsonObject ODataGetOperation(TableModel table) => new()
    {
        ["summary"] = $"Get a {table.ExposedName} by key",
        ["responses"] = new JsonObject
        {
            ["200"] = JsonResponse($"#/components/schemas/{table.ExposedName}"),
            ["404"] = new JsonObject { ["description"] = "Not found" },
        },
    };

    private static JsonObject ODataCreateOperation(TableModel table) => new()
    {
        ["summary"] = $"Create a {table.ExposedName}",
        ["requestBody"] = RequestBody($"#/components/schemas/{table.ExposedName}Create"),
        ["responses"] = new JsonObject
        {
            ["201"] = JsonResponse($"#/components/schemas/{table.ExposedName}"),
            ["400"] = new JsonObject { ["description"] = "Validation error" },
            ["409"] = new JsonObject { ["description"] = "Conflict" },
        },
    };

    private static JsonObject ODataUpdateOperation(TableModel table) => new()
    {
        ["summary"] = $"Update a {table.ExposedName}",
        ["requestBody"] = RequestBody($"#/components/schemas/{table.ExposedName}Update"),
        ["responses"] = new JsonObject
        {
            ["200"] = JsonResponse($"#/components/schemas/{table.ExposedName}"),
            ["404"] = new JsonObject { ["description"] = "Not found" },
        },
    };

    private static JsonObject DeleteOperation(TableModel table) => new()
    {
        ["summary"] = $"Delete a {table.ExposedName}",
        ["responses"] = new JsonObject
        {
            ["204"] = new JsonObject { ["description"] = "Deleted" },
            ["404"] = new JsonObject { ["description"] = "Not found" },
        },
    };

    private static string KeyTemplate(TableModel table) =>
        table.PrimaryKey.Count == 1 ? "{id}" : string.Join(",", table.PrimaryKey.Select(k => $"{k}={{{k}}}"));

    private static JsonObject QueryParam(string name, string description, string type = "string") => new()
    {
        ["name"] = name,
        ["in"] = "query",
        ["required"] = false,
        ["description"] = description,
        ["schema"] = new JsonObject { ["type"] = type },
    };

    private static JsonObject OkArrayResponse(TableModel table) => new()
    {
        ["200"] = new JsonObject
        {
            ["description"] = "Success",
            ["content"] = new JsonObject
            {
                ["application/json"] = new JsonObject
                {
                    ["schema"] = new JsonObject
                    {
                        ["type"] = "object",
                        ["properties"] = new JsonObject
                        {
                            ["value"] = new JsonObject
                            {
                                ["type"] = "array",
                                ["items"] = Ref($"#/components/schemas/{table.ExposedName}"),
                            },
                        },
                    },
                },
            },
        },
    };

    private static JsonObject JsonResponse(string schemaRef) => new()
    {
        ["description"] = "Success",
        ["content"] = new JsonObject
        {
            ["application/json"] = new JsonObject { ["schema"] = Ref(schemaRef) },
        },
    };

    private static JsonObject RequestBody(string schemaRef) => new()
    {
        ["required"] = true,
        ["content"] = new JsonObject
        {
            ["application/json"] = new JsonObject { ["schema"] = Ref(schemaRef) },
        },
    };

    private static JsonObject Ref(string path) => new() { ["$ref"] = path };
}
