using EzOdata.Connectors.Abstractions;
using EzOdata.Core.Schema;
using Microsoft.Data.Sqlite;

namespace EzOdata.Connectors.Sqlite;

/// <summary>Pragma-based introspection (spec 04 §4): table_xinfo, foreign_key_list, index_list.</summary>
public sealed class SqliteIntrospector : ISchemaIntrospector
{
    public async Task<SchemaSnapshot> IntrospectAsync(ConnectionSpec spec, IntrospectionOptions options, CancellationToken ct)
    {
        using var connection = new SqliteConnection(SqliteConnector.BuildConnectionString(spec));
        await connection.OpenAsync(ct);

        var rawTables = new List<(string Name, bool IsView, string? Sql)>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT name, type, sql FROM sqlite_master
                WHERE type IN ('table', 'view') AND name NOT LIKE 'sqlite_%'
                ORDER BY name
                """;
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                rawTables.Add((reader.GetString(0), reader.GetString(1) == "view",
                    reader.IsDBNull(2) ? null : reader.GetString(2)));
            }
        }

        var included = rawTables
            .Where(t => options.ExcludeTables.Count == 0 || !Core.Text.Glob.MatchesAny(t.Name, options.ExcludeTables))
            .Where(t => options.IncludeViews || !t.IsView)
            .ToList();

        var tables = new List<TableModel>();
        foreach (var (name, isView, createSql) in included)
        {
            var columns = new List<ColumnModel>();
            var primaryKey = new List<string>();

            using (var command = connection.CreateCommand())
            {
                command.CommandText = $"PRAGMA table_xinfo({Quote(name)})";
                using var reader = await command.ExecuteReaderAsync(ct);
                var pkOrder = new List<(string Column, long Order)>();
                while (await reader.ReadAsync(ct))
                {
                    var hidden = reader.GetInt64(reader.GetOrdinal("hidden"));
                    if (hidden is 1) continue; // hidden/generated virtual columns

                    var columnName = reader.GetString(reader.GetOrdinal("name"));
                    var declaredType = reader.IsDBNull(reader.GetOrdinal("type")) ? "" : reader.GetString(reader.GetOrdinal("type"));
                    var notNull = reader.GetInt64(reader.GetOrdinal("notnull")) == 1;
                    var pk = reader.GetInt64(reader.GetOrdinal("pk"));
                    var defaultValue = reader.IsDBNull(reader.GetOrdinal("dflt_value"))
                        ? null
                        : reader.GetString(reader.GetOrdinal("dflt_value"));

                    var (edmType, fallback) = MapType(declaredType);
                    columns.Add(new ColumnModel
                    {
                        DbName = columnName,
                        ExposedName = columnName,
                        DbType = declaredType.Length == 0 ? "blob" : declaredType.ToLowerInvariant(),
                        EdmType = edmType,
                        IsFallbackType = fallback,
                        Nullable = !notNull && pk == 0,
                        IsPrimaryKey = pk > 0,
                        DefaultExpression = defaultValue,
                        IsComputed = hidden is 2 or 3,
                    });
                    if (pk > 0) pkOrder.Add((columnName, pk));
                }

                primaryKey = pkOrder.OrderBy(p => p.Order).Select(p => p.Column).ToList();
            }

            // Single INTEGER pk = rowid alias → auto-generated (spec 04 §4)
            if (primaryKey.Count == 1)
            {
                var index = columns.FindIndex(c => c.ExposedName == primaryKey[0]);
                if (index >= 0 && columns[index].EdmType is "Edm.Int64" or "Edm.Int32" && !isView)
                {
                    columns[index] = columns[index] with { IsAutoGenerated = true };
                }
            }

            var uniques = new List<IReadOnlyList<string>>();
            if (!isView)
            {
                using var indexCommand = connection.CreateCommand();
                indexCommand.CommandText = $"PRAGMA index_list({Quote(name)})";
                var uniqueIndexNames = new List<string>();
                using (var reader = await indexCommand.ExecuteReaderAsync(ct))
                {
                    while (await reader.ReadAsync(ct))
                    {
                        if (reader.GetInt64(reader.GetOrdinal("unique")) == 1
                            && reader.GetString(reader.GetOrdinal("origin")) == "u")
                        {
                            uniqueIndexNames.Add(reader.GetString(reader.GetOrdinal("name")));
                        }
                    }
                }

                foreach (var indexName in uniqueIndexNames)
                {
                    using var infoCommand = connection.CreateCommand();
                    infoCommand.CommandText = $"PRAGMA index_info({Quote(indexName)})";
                    var indexColumns = new List<string>();
                    using var reader = await infoCommand.ExecuteReaderAsync(ct);
                    while (await reader.ReadAsync(ct))
                    {
                        if (!reader.IsDBNull(reader.GetOrdinal("name")))
                        {
                            indexColumns.Add(reader.GetString(reader.GetOrdinal("name")));
                        }
                    }

                    if (indexColumns.Count > 0) uniques.Add(indexColumns);
                }
            }

            tables.Add(new TableModel
            {
                DbSchema = "",
                DbName = name,
                ExposedName = name,
                IsView = isView,
                Writable = !isView,
                Columns = columns,
                PrimaryKey = primaryKey,
                UniqueConstraints = uniques,
            });
        }

        // Foreign keys (second pass: all tables known)
        var includedNames = new HashSet<string>(tables.Select(t => t.ExposedName), StringComparer.Ordinal);
        for (var i = 0; i < tables.Count; i++)
        {
            var table = tables[i];
            if (table.IsView) continue;

            using var command = connection.CreateCommand();
            command.CommandText = $"PRAGMA foreign_key_list({Quote(table.DbName)})";

            var raw = new List<(long Id, string RefTable, string From, string To)>();
            using (var reader = await command.ExecuteReaderAsync(ct))
            {
                while (await reader.ReadAsync(ct))
                {
                    raw.Add((
                        reader.GetInt64(reader.GetOrdinal("id")),
                        reader.GetString(reader.GetOrdinal("table")),
                        reader.GetString(reader.GetOrdinal("from")),
                        reader.IsDBNull(reader.GetOrdinal("to")) ? "" : reader.GetString(reader.GetOrdinal("to"))));
                }
            }

            var childTaken = new HashSet<string>(table.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
            var fks = new List<ForeignKeyModel>();
            foreach (var group in raw.GroupBy(r => r.Id).OrderBy(g => g.Key))
            {
                var refTable = group.First().RefTable;
                if (!includedNames.Contains(refTable)) continue;

                var parent = tables.First(t => t.ExposedName == refTable);
                var parentTaken = new HashSet<string>(parent.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
                foreach (var existing in parent.ForeignKeys) parentTaken.Add(existing.NavToMany);

                var fkName = $"fk_{table.DbName}_{group.Key}";
                var fromColumns = group.Select(g => g.From).ToList();
                var toColumns = group.Select(g => string.IsNullOrEmpty(g.To) ? parent.PrimaryKey.FirstOrDefault() ?? "" : g.To).ToList();

                fks.Add(new ForeignKeyModel
                {
                    Name = fkName,
                    Columns = fromColumns,
                    RefTable = refTable,
                    RefColumns = toColumns,
                    NavToOne = NavigationNaming.ToOneName(fromColumns, refTable, fkName, childTaken),
                    NavToMany = NavigationNaming.ToManyName(table.ExposedName, fkName, parentTaken),
                });
            }

            tables[i] = table with { ForeignKeys = fks };
        }

        return new SchemaSnapshot
        {
            Engine = "sqlite",
            CollectedAt = DateTimeOffset.UtcNow,
            Tables = tables.OrderBy(t => t.ExposedName, StringComparer.Ordinal).ToList(),
        };
    }

    private static string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"") + "\"";

    public static (string EdmType, bool IsFallback) MapType(string declared)
    {
        var upper = declared.ToUpperInvariant();
        if (upper.Contains("BOOL")) return ("Edm.Boolean", false);
        if (upper.Contains("DATETIME") || upper.Contains("TIMESTAMP")) return ("Edm.DateTimeOffset", false);
        if (upper.Contains("DATE")) return ("Edm.Date", false);
        if (upper.Contains("TIME")) return ("Edm.TimeOfDay", false);
        if (upper.Contains("GUID") || upper.Contains("UUID")) return ("Edm.Guid", false);
        if (upper.Contains("JSON")) return ("Edm.Untyped", false);
        if (upper.Contains("INT")) return ("Edm.Int64", false);
        if (upper.Contains("CHAR") || upper.Contains("TEXT") || upper.Contains("CLOB")) return ("Edm.String", false);
        if (upper.Contains("REAL") || upper.Contains("FLOA") || upper.Contains("DOUB")) return ("Edm.Double", false);
        if (upper.Contains("DEC") || upper.Contains("NUMERIC") || upper.Contains("MONEY")) return ("Edm.Decimal", false);
        if (upper.Contains("BLOB") || upper.Length == 0) return ("Edm.Binary", false);
        return ("Edm.String", true);
    }
}
