import { describe, expect, it } from "vitest";
import type { RowFilterParser } from "../../../src/core/policy/contracts.js";
import { PolicyEngine } from "../../../src/core/policy/engine.js";
import { trimSnapshot } from "../../../src/core/policy/trimmer.js";
import {
  ANONYMOUS_IDENTITY,
  DEV_BYPASS_IDENTITY,
  Verb,
} from "../../../src/core/policy/model.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";

/**
 * RequestIdentity.bypass short-circuits PolicyEngine and snapshot trimming
 * (port of BypassIdentityTests.cs).
 */
describe("Bypass identity", () => {
  const engine = new PolicyEngine();

  const failParser: RowFilterParser = () => {
    throw new Error("RowFilterParser must not be called for a bypass identity.");
  };

  // ---- PolicyEngine ----

  it("grants full access regardless of rules", () => {
    const decision = engine.authorize(
      DEV_BYPASS_IDENTITY,
      [],
      "sales",
      "orders",
      Verb.Delete,
      ["id", "total", "ssn"],
      failParser,
    );
    expect(decision.allowed).toBe(true);
    expect(decision.bypass).toBe(true);
    expect(decision.deniedFields.size).toBe(0);
  });

  it("never calls the row-filter parser for a bypass identity", () => {
    const decision = engine.authorize(DEV_BYPASS_IDENTITY, [], "s", "t", Verb.Get, ["id"], failParser);
    expect(decision.allowed).toBe(true);
  });

  it("does not treat the anonymous identity as a bypass", () => {
    expect(ANONYMOUS_IDENTITY.bypass).toBe(false);
    expect(DEV_BYPASS_IDENTITY.bypass).toBe(true);
  });

  // ---- snapshot trimming ----

  it("returns an untrimmed snapshot for a bypass identity", () => {
    const snapshot: SchemaSnapshot = {
      version: 1,
      engine: "postgresql",
      collectedAt: new Date(0).toISOString(),
      tables: [
        {
          dbSchema: "public",
          dbName: "secrets",
          exposedName: "secrets",
          isView: false,
          writable: true,
          primaryKey: ["id"],
          uniqueConstraints: [],
          foreignKeys: [],
          columns: [
            col("id", "Edm.Int32", { isPrimaryKey: true }),
            col("ssn", "Edm.String"),
          ],
        },
        {
          dbSchema: "public",
          dbName: "hidden",
          exposedName: "hidden",
          isView: false,
          writable: true,
          primaryKey: ["id"],
          uniqueConstraints: [],
          foreignKeys: [],
          columns: [col("id", "Edm.Int32", { isPrimaryKey: true })],
        },
      ],
    };

    const trimmed = trimSnapshot(snapshot, DEV_BYPASS_IDENTITY, [], "sales", engine, failParser);
    expect(trimmed.tables.length).toBe(2);
    const secrets = trimmed.tables.find((t) => t.exposedName === "secrets")!;
    expect(secrets.columns.length).toBe(2); // ssn not stripped
  });
});

function col(name: string, edmType: string, extra: { isPrimaryKey?: boolean } = {}) {
  return {
    dbName: name,
    exposedName: name,
    dbType: "x",
    edmType,
    nullable: true,
    isPrimaryKey: extra.isPrimaryKey ?? false,
    isAutoGenerated: false,
    isComputed: false,
    isFallbackType: false,
  };
}
