import { describe, expect, it } from "vitest";
import { comparison, constant, fieldRef, fn, logical, not, type QueryRequest } from "../../../src/core/query.js";
import { FULL_ACCESS } from "../../../src/core/policy/decision.js";
import { FieldDeniedError, masksToApply, rewrite } from "../../../src/core/policy/rewriter.js";
import type { PolicyDecision } from "../../../src/core/policy/decision.js";
import type { TableModel } from "../../../src/core/schema.js";

const CUSTOMERS: TableModel = {
  dbSchema: "public",
  dbName: "customers",
  exposedName: "customers",
  isView: false,
  writable: true,
  columns: [
    { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
    { dbName: "name", exposedName: "name", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
    { dbName: "email", exposedName: "email", dbType: "text", edmType: "Edm.String", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
    { dbName: "ssn", exposedName: "ssn", dbType: "text", edmType: "Edm.String", nullable: true, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
  ],
  primaryKey: ["id"],
  uniqueConstraints: [],
  foreignKeys: [],
};

function baseQuery(): QueryRequest {
  return {
    serviceName: "sales",
    table: "customers",
    orderBy: [],
    expand: [],
    count: false,
  };
}

function denySsn(): PolicyDecision {
  return {
    allowed: true,
    hidden: false,
    bypass: false,
    deniedFields: new Set(["ssn"]),
    maskedFields: new Map(),
    writeOnlyFields: new Set(),
  };
}

describe("QueryPolicyRewriter", () => {
  it("implicit select excludes denied fields", () => {
    const rewritten = rewrite(baseQuery(), denySsn(), CUSTOMERS);
    expect(rewritten.select).toBeDefined();
    expect(rewritten.select).not.toContain("ssn");
    expect(rewritten.select).toContain("name");
  });

  it("explicit select of denied field throws FieldDeniedError", () => {
    const q = { ...baseQuery(), select: ["id", "ssn"] as const };
    expect(() => rewrite(q, denySsn(), CUSTOMERS)).toThrow(FieldDeniedError);
    try {
      rewrite(q, denySsn(), CUSTOMERS);
    } catch (e) {
      expect((e as FieldDeniedError).field).toBe("ssn");
    }
  });

  it("filter on denied field throws FieldDeniedError", () => {
    const q = { ...baseQuery(), filter: comparison(fieldRef("ssn"), "eq", constant("111-22-3333")) };
    expect(() => rewrite(q, denySsn(), CUSTOMERS)).toThrow(FieldDeniedError);
  });

  it("function arg on denied field throws", () => {
    const q = {
      ...baseQuery(),
      filter: fn("contains", [{ kind: "field" as const, field: fieldRef("ssn") }, { kind: "constant" as const, value: constant("111") }]),
    };
    expect(() => rewrite(q, denySsn(), CUSTOMERS)).toThrow(FieldDeniedError);
  });

  it("orderby on denied field throws", () => {
    const q = { ...baseQuery(), orderBy: [{ field: "ssn", descending: false }] };
    expect(() => rewrite(q, denySsn(), CUSTOMERS)).toThrow(FieldDeniedError);
  });

  it("nested filter still caught", () => {
    const q = {
      ...baseQuery(),
      filter: logical("or", [
        comparison(fieldRef("name"), "eq", constant("x")),
        not(comparison(fieldRef("ssn"), "ne", constant(null))),
      ]),
    };
    expect(() => rewrite(q, denySsn(), CUSTOMERS)).toThrow(FieldDeniedError);
  });

  it("masked fields removed from SQL but reported for serialization", () => {
    const decision: PolicyDecision = {
      allowed: true,
      hidden: false,
      bypass: false,
      deniedFields: new Set(),
      maskedFields: new Map([["email", "***@***"]]),
      writeOnlyFields: new Set(),
    };
    const q = baseQuery();
    const rewritten = rewrite(q, decision, CUSTOMERS);
    expect(rewritten.select).not.toContain("email");
    expect(masksToApply(q, decision).get("email")).toBe("***@***");
  });

  it("masked field is not filterable", () => {
    const decision: PolicyDecision = {
      allowed: true,
      hidden: false,
      bypass: false,
      deniedFields: new Set(),
      maskedFields: new Map([["email", "***"]]),
      writeOnlyFields: new Set(),
    };
    const q = { ...baseQuery(), filter: comparison(fieldRef("email"), "eq", constant("x@y.z")) };
    expect(() => rewrite(q, decision, CUSTOMERS)).toThrow(FieldDeniedError);
  });

  it("masked field in explicit select allowed but stripped from SQL", () => {
    const decision: PolicyDecision = {
      allowed: true,
      hidden: false,
      bypass: false,
      deniedFields: new Set(),
      maskedFields: new Map([["email", "***"]]),
      writeOnlyFields: new Set(),
    };
    const q = { ...baseQuery(), select: ["id", "email"] as const };
    const rewritten = rewrite(q, decision, CUSTOMERS);
    expect(rewritten.select).toEqual(["id"]);
    expect(masksToApply(q, decision).get("email")).toBe("***");
  });

  it("row filter is ANDed with client filter", () => {
    const rowFilter = comparison(fieldRef("country"), "eq", constant("US"));
    const clientFilter = comparison(fieldRef("name"), "eq", constant("Acme"));
    const decision: PolicyDecision = {
      allowed: true,
      hidden: false,
      bypass: false,
      deniedFields: new Set(),
      maskedFields: new Map(),
      writeOnlyFields: new Set(),
      rowFilter,
    };
    const rewritten = rewrite({ ...baseQuery(), filter: clientFilter }, decision, CUSTOMERS);
    expect(rewritten.filter?.kind).toBe("logical");
    const and = rewritten.filter as { kind: "logical"; op: string; operands: unknown[] };
    expect(and.op).toBe("and");
    expect(and.operands).toContain(clientFilter);
    expect(and.operands).toContain(rowFilter);
  });

  it("bypass decision leaves query untouched", () => {
    const q = { ...baseQuery(), select: ["ssn"] as const };
    const rewritten = rewrite(q, FULL_ACCESS, CUSTOMERS);
    expect(rewritten).toBe(q);
  });

  it("masksToApply returns empty map when originalQuery.select excludes masked field", () => {
    const decision: PolicyDecision = {
      allowed: true,
      hidden: false,
      bypass: false,
      deniedFields: new Set(),
      maskedFields: new Map([["ssn", "***"]]),
      writeOnlyFields: new Set(),
    };
    const q = { ...baseQuery(), select: ["id", "name"] as const };
    const masks = masksToApply(q, decision);
    expect(masks.size).toBe(0);
  });
});
