using EzOdata.Connectors.Abstractions;
using EzOdata.Core.Schema;
using Microsoft.Data.SqlClient;

namespace EzOdata.Connectors.SqlServer;

/// <summary>INFORMATION_SCHEMA + sys catalog introspection for SQL Server (spec 04 §4).</summary>
public sealed class SqlServerIntrospector : ISchemaIntrospector
{
    public async Task<SchemaSnapshot> IntrospectAsync(ConnectionSpec spec, IntrospectionOptions options, CancellationToken ct)
    {
        using var connection = new SqlConnection(SqlServerConnector.BuildConnectionString(spec, 15));
        await connection.OpenAsync(ct);

        // Tables + views (+ MS_Description comments)
        var rawTables = new List<(string Schema, string Name, bool IsView, string? Comment)>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT s.name, o.name, o.type, CAST(ep.value AS nvarchar(max))
                FROM sys.objects o
                JOIN sys.schemas s ON s.schema_id = o.schema_id
                LEFT JOIN sys.extended_properties ep
                  ON ep.major_id = o.object_id AND ep.minor_id = 0 AND ep.name = 'MS_Description'
                WHERE o.type IN ('U', 'V')
                ORDER BY s.name, o.name
                """;
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                rawTables.Add((reader.GetString(0), reader.GetString(1),
                    reader.GetString(2).Trim() == "V",
                    reader.IsDBNull(3) ? null : reader.GetString(3)));
            }
        }

        var included = rawTables
            .Where(t => options.IncludeSchemas.Count == 0 || Core.Text.Glob.MatchesAny(t.Schema, options.IncludeSchemas))
            .Where(t => options.ExcludeTables.Count == 0 || !Core.Text.Glob.MatchesAny(t.Name, options.ExcludeTables))
            .Where(t => options.IncludeViews || !t.IsView)
            .ToList();
        var includedKeys = new HashSet<(string, string)>(included.Select(t => (t.Schema, t.Name)));

        // Columns
        var columnsByTable = new Dictionary<(string, string), List<ColumnModel>>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT c.TABLE_SCHEMA, c.TABLE_NAME, c.COLUMN_NAME, c.ORDINAL_POSITION, c.DATA_TYPE,
                       CASE WHEN c.IS_NULLABLE = 'YES' THEN 1 ELSE 0 END,
                       c.CHARACTER_MAXIMUM_LENGTH, c.NUMERIC_PRECISION, c.NUMERIC_SCALE, c.COLUMN_DEFAULT,
                       COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsIdentity'),
                       COLUMNPROPERTY(OBJECT_ID(QUOTENAME(c.TABLE_SCHEMA) + '.' + QUOTENAME(c.TABLE_NAME)), c.COLUMN_NAME, 'IsComputed')
                FROM INFORMATION_SCHEMA.COLUMNS c
                ORDER BY c.TABLE_SCHEMA, c.TABLE_NAME, c.ORDINAL_POSITION
                """;
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                var key = (reader.GetString(0), reader.GetString(1));
                if (!includedKeys.Contains(key)) continue;

                var (edmType, fallback) = MapType(reader.GetString(4));
                if (!columnsByTable.TryGetValue(key, out var list))
                {
                    columnsByTable[key] = list = [];
                }

                var maxLength = reader.IsDBNull(6) ? (int?)null : reader.GetInt32(6);
                list.Add(new ColumnModel
                {
                    DbName = reader.GetString(2),
                    ExposedName = reader.GetString(2),
                    DbType = reader.GetString(4),
                    EdmType = edmType,
                    IsFallbackType = fallback,
                    Nullable = reader.GetInt32(5) == 1,
                    MaxLength = maxLength == -1 ? null : maxLength, // -1 = MAX
                    Precision = reader.IsDBNull(7) ? null : Convert.ToInt32(reader.GetValue(7)),
                    Scale = reader.IsDBNull(8) ? null : Convert.ToInt32(reader.GetValue(8)),
                    DefaultExpression = reader.IsDBNull(9) ? null : reader.GetString(9),
                    IsAutoGenerated = !reader.IsDBNull(10) && reader.GetInt32(10) == 1,
                    IsComputed = !reader.IsDBNull(11) && reader.GetInt32(11) == 1,
                });
            }
        }

        // Keys
        var keysByTable = new Dictionary<(string, string), List<(string Constraint, bool IsPrimary, string Column, int Ordinal)>>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT tc.TABLE_SCHEMA, tc.TABLE_NAME, tc.CONSTRAINT_NAME,
                       CASE WHEN tc.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 1 ELSE 0 END,
                       kcu.COLUMN_NAME, kcu.ORDINAL_POSITION
                FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
                JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
                  ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME AND kcu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
                WHERE tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE')
                ORDER BY tc.TABLE_SCHEMA, tc.TABLE_NAME, tc.CONSTRAINT_NAME, kcu.ORDINAL_POSITION
                """;
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                var key = (reader.GetString(0), reader.GetString(1));
                if (!includedKeys.Contains(key)) continue;
                if (!keysByTable.TryGetValue(key, out var list))
                {
                    keysByTable[key] = list = [];
                }

                list.Add((reader.GetString(2), reader.GetInt32(3) == 1, reader.GetString(4), reader.GetInt32(5)));
            }
        }

        // Foreign keys via sys catalog (ordered composite columns)
        var fksRaw = new List<(string Name, string Schema, string Table, string Column, string RefSchema, string RefTable, string RefColumn, int Ordinal)>();
        using (var command = connection.CreateCommand())
        {
            command.CommandText = """
                SELECT fk.name, ps.name, pt.name, pc.name, rs.name, rt.name, rc.name, fkc.constraint_column_id
                FROM sys.foreign_keys fk
                JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id = fk.object_id
                JOIN sys.tables pt ON pt.object_id = fk.parent_object_id
                JOIN sys.schemas ps ON ps.schema_id = pt.schema_id
                JOIN sys.columns pc ON pc.object_id = fkc.parent_object_id AND pc.column_id = fkc.parent_column_id
                JOIN sys.tables rt ON rt.object_id = fk.referenced_object_id
                JOIN sys.schemas rs ON rs.schema_id = rt.schema_id
                JOIN sys.columns rc ON rc.object_id = fkc.referenced_object_id AND rc.column_id = fkc.referenced_column_id
                ORDER BY fk.name, fkc.constraint_column_id
                """;
            using var reader = await command.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                fksRaw.Add((reader.GetString(0), reader.GetString(1), reader.GetString(2), reader.GetString(3),
                    reader.GetString(4), reader.GetString(5), reader.GetString(6), reader.GetInt32(7)));
            }
        }

        var tables = new List<TableModel>();
        foreach (var (schemaName, name, isView, comment) in included)
        {
            var key = (schemaName, name);
            var keys = keysByTable.TryGetValue(key, out var keyList) ? keyList : [];
            var pkColumns = keys.Where(k => k.IsPrimary).OrderBy(k => k.Ordinal).Select(k => k.Column).ToList();
            var pkSet = new HashSet<string>(pkColumns, StringComparer.Ordinal);
            var columns = columnsByTable.TryGetValue(key, out var cols) ? cols : [];
            for (var c = 0; c < columns.Count; c++)
            {
                if (pkSet.Contains(columns[c].ExposedName))
                {
                    columns[c] = columns[c] with { IsPrimaryKey = true, Nullable = false };
                }
            }

            tables.Add(new TableModel
            {
                DbSchema = schemaName,
                DbName = name,
                ExposedName = schemaName == "dbo" ? name : $"{schemaName}_{name}",
                IsView = isView,
                Writable = !isView,
                Comment = comment,
                Columns = columns,
                PrimaryKey = pkColumns,
                UniqueConstraints = keys.Where(k => !k.IsPrimary)
                    .GroupBy(k => k.Constraint)
                    .Select(g => (IReadOnlyList<string>)g.OrderBy(k => k.Ordinal).Select(k => k.Column).ToList())
                    .ToList(),
            });
        }

        for (var i = 0; i < tables.Count; i++)
        {
            var table = tables[i];
            var childTaken = new HashSet<string>(table.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
            var fks = new List<ForeignKeyModel>();

            foreach (var group in fksRaw
                .Where(f => f.Schema == table.DbSchema && f.Table == table.DbName)
                .GroupBy(f => f.Name).OrderBy(g => g.Key))
            {
                var first = group.First();
                var parent = tables.FirstOrDefault(t => t.DbSchema == first.RefSchema && t.DbName == first.RefTable);
                if (parent is null) continue;

                var parentTaken = new HashSet<string>(parent.Columns.Select(c => c.ExposedName), StringComparer.Ordinal);
                foreach (var existing in parent.ForeignKeys) parentTaken.Add(existing.NavToMany);

                var ordered = group.OrderBy(g => g.Ordinal).ToList();
                var fromColumns = ordered.Select(g => g.Column).ToList();
                fks.Add(new ForeignKeyModel
                {
                    Name = group.Key,
                    Columns = fromColumns,
                    RefTable = parent.ExposedName,
                    RefColumns = ordered.Select(g => g.RefColumn).ToList(),
                    NavToOne = NavigationNaming.ToOneName(fromColumns, parent.ExposedName, group.Key, childTaken),
                    NavToMany = NavigationNaming.ToManyName(table.ExposedName, group.Key, parentTaken),
                });
            }

            tables[i] = table with { ForeignKeys = fks };
        }

        return new SchemaSnapshot
        {
            Engine = "sqlserver",
            CollectedAt = DateTimeOffset.UtcNow,
            Tables = tables.OrderBy(t => t.ExposedName, StringComparer.Ordinal).ToList(),
        };
    }

    public static (string EdmType, bool Fallback) MapType(string dataType) => dataType.ToLowerInvariant() switch
    {
        "tinyint" or "smallint" => ("Edm.Int16", false),
        "int" => ("Edm.Int32", false),
        "bigint" => ("Edm.Int64", false),
        "decimal" or "numeric" or "money" or "smallmoney" => ("Edm.Decimal", false),
        "float" => ("Edm.Double", false),
        "real" => ("Edm.Single", false),
        "bit" => ("Edm.Boolean", false),
        "char" or "varchar" or "text" or "nchar" or "nvarchar" or "ntext" => ("Edm.String", false),
        "uniqueidentifier" => ("Edm.Guid", false),
        "datetime2" or "datetimeoffset" or "datetime" or "smalldatetime" => ("Edm.DateTimeOffset", false),
        "date" => ("Edm.Date", false),
        "time" => ("Edm.TimeOfDay", false),
        "binary" or "varbinary" or "image" or "rowversion" or "timestamp" => ("Edm.Binary", false),
        _ => ("Edm.String", true),
    };
}
