using System.Globalization;
using System.Text.Json;
using EzOdata.Core.Schema;

namespace EzOdata.Core.Query;

/// <summary>
/// JSON write payload → typed RecordPayload (spec 05 §5.1): strict coercion (no silent
/// string→int), unknown properties rejected, auto-generated/computed columns rejected,
/// enum allowed-values enforced. Write-only policy fields are bindable by design.
/// </summary>
public static class PayloadBinder
{
    public sealed class BindException : Exception
    {
        public BindException(string errorCode, string message) : base(message) => ErrorCode = errorCode;

        public string ErrorCode { get; }
    }

    public static RecordPayload Bind(
        JsonElement json, TableModel table, SchemaSnapshot schema,
        bool allowDeepInsert, bool isReplace = false)
    {
        if (json.ValueKind != JsonValueKind.Object)
        {
            throw new BindException(ErrorCodes.ValidationInvalidValue, "Record payload must be a JSON object.");
        }

        var values = new Dictionary<string, object?>(StringComparer.Ordinal);
        var children = new Dictionary<string, IReadOnlyList<RecordPayload>>(StringComparer.Ordinal);

        foreach (var property in json.EnumerateObject())
        {
            if (property.Name.StartsWith("@", StringComparison.Ordinal))
            {
                continue; // OData control information is ignored on input
            }

            var column = table.FindColumn(property.Name);
            if (column is not null)
            {
                if (column.IsAutoGenerated || column.IsComputed)
                {
                    throw new BindException(ErrorCodes.ValidationInvalidValue,
                        $"Property '{property.Name}' is generated by the database and cannot be written.");
                }

                values[property.Name] = Coerce(property.Value, column);
                continue;
            }

            // Deep insert: a to-many navigation with an array payload (spec 05 §5.1)
            var childTable = FindChildByNav(schema, table, property.Name);
            if (childTable is not null && property.Value.ValueKind == JsonValueKind.Array)
            {
                if (!allowDeepInsert)
                {
                    throw new BindException(ErrorCodes.ValidationInvalidValue,
                        $"Nested collection '{property.Name}' is only supported on create (deep insert).");
                }

                children[property.Name] = property.Value.EnumerateArray()
                    .Select(child => Bind(child, childTable, schema, allowDeepInsert: false))
                    .ToList();
                continue;
            }

            throw new BindException(ErrorCodes.ValidationUnknownProperty,
                $"Unknown property '{property.Name}' on '{table.ExposedName}'.");
        }

        if (isReplace)
        {
            // PUT semantics (spec 04 §7.3): missing writable non-key columns → NULL or default.
            foreach (var column in table.Columns)
            {
                if (column.IsPrimaryKey || column.IsAutoGenerated || column.IsComputed) continue;
                if (values.ContainsKey(column.ExposedName)) continue;

                if (column.Nullable)
                {
                    values[column.ExposedName] = null;
                }
                else if (column.DefaultExpression is null)
                {
                    throw new BindException(ErrorCodes.ValidationNotNullViolation,
                        $"Replace requires a value for non-nullable property '{column.ExposedName}'.");
                }
                // non-nullable WITH default: omit → database default applies
            }
        }

        return new RecordPayload { Values = values, Children = children };
    }

    private static TableModel? FindChildByNav(SchemaSnapshot schema, TableModel parent, string navigation)
    {
        foreach (var candidate in schema.Tables)
        {
            if (candidate.ForeignKeys.Any(fk => fk.RefTable == parent.ExposedName && fk.NavToMany == navigation))
            {
                return candidate;
            }
        }

        return null;
    }

    internal static object? Coerce(JsonElement value, ColumnModel column)
    {
        if (value.ValueKind is JsonValueKind.Null)
        {
            if (!column.Nullable)
            {
                throw new BindException(ErrorCodes.ValidationNotNullViolation,
                    $"Property '{column.ExposedName}' cannot be null.");
            }

            return null;
        }

        try
        {
            var result = CoerceCore(value, column);

            if (column.AllowedValues is { Count: > 0 } allowed && result is string s && !allowed.Contains(s))
            {
                throw new BindException(ErrorCodes.ValidationInvalidValue,
                    $"'{s}' is not an allowed value for '{column.ExposedName}'.");
            }

            if (column.MaxLength is { } max && result is string text && text.Length > max)
            {
                throw new BindException(ErrorCodes.ValidationValueTooLong,
                    $"Value for '{column.ExposedName}' exceeds max length {max}.");
            }

            return result;
        }
        catch (BindException)
        {
            throw;
        }
        catch (Exception ex) when (ex is FormatException or InvalidOperationException or OverflowException or JsonException)
        {
            throw new BindException(ErrorCodes.ValidationInvalidValue,
                $"Value for '{column.ExposedName}' is not a valid {column.EdmType}.");
        }
    }

    private static object CoerceCore(JsonElement value, ColumnModel column) => column.EdmType switch
    {
        "Edm.Int16" => RequireNumber(value, column).GetInt16(),
        "Edm.Int32" => RequireNumber(value, column).GetInt32(),
        "Edm.Int64" => RequireNumber(value, column).GetInt64(),
        "Edm.Decimal" => RequireNumber(value, column).GetDecimal(),
        "Edm.Double" => RequireNumber(value, column).GetDouble(),
        "Edm.Single" => (float)RequireNumber(value, column).GetDouble(),
        "Edm.Boolean" when value.ValueKind is JsonValueKind.True or JsonValueKind.False => value.GetBoolean(),
        "Edm.Boolean" => throw new BindException(ErrorCodes.ValidationInvalidValue,
            $"Property '{column.ExposedName}' must be a boolean."),
        "Edm.String" => RequireString(value, column),
        "Edm.Guid" => Guid.Parse(RequireString(value, column)),
        "Edm.DateTimeOffset" => DateTimeOffset.Parse(RequireString(value, column), CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
        "Edm.Date" => DateTime.ParseExact(RequireString(value, column), "yyyy-MM-dd", CultureInfo.InvariantCulture),
        "Edm.TimeOfDay" => TimeSpan.Parse(RequireString(value, column), CultureInfo.InvariantCulture),
        "Edm.Binary" => Convert.FromBase64String(RequireString(value, column)),
        "Edm.Untyped" => value.GetRawText(),
        _ => RequireString(value, column), // fallback-typed columns accept strings
    };

    private static JsonElement RequireNumber(JsonElement value, ColumnModel column) =>
        value.ValueKind == JsonValueKind.Number
            ? value
            : throw new BindException(ErrorCodes.ValidationInvalidValue,
                $"Property '{column.ExposedName}' must be a number (strict coercion, spec 05 §5.1).");

    private static string RequireString(JsonElement value, ColumnModel column) =>
        value.ValueKind == JsonValueKind.String
            ? value.GetString()!
            : throw new BindException(ErrorCodes.ValidationInvalidValue,
                $"Property '{column.ExposedName}' must be a string.");
}
