/**
 * MCP server unit tests (port of McpServerTests.cs, spec 09).
 * Uses stub executors — no database required.
 */

import { describe, expect, it, vi } from "vitest";
import { McpServer, type McpHandlerConfig, type VisibleServicesProvider } from "../../../src/mcp/server.js";
import { PolicyEngine } from "../../../src/core/policy/engine.js";
import { DEV_BYPASS_IDENTITY } from "../../../src/core/policy/model.js";
import type { ServiceRuntime, QueryExecutor, WriteExecutor } from "../../../src/connectors/contracts.js";
import { Row } from "../../../src/core/result.js";
import { DEFAULT_SERVICE_OPTIONS } from "../../../src/core/services.js";
import type { SchemaSnapshot } from "../../../src/core/schema.js";

const SCHEMA: SchemaSnapshot = {
  version: 1,
  engine: "postgresql",
  collectedAt: "2026-01-01T00:00:00Z",
  tables: [
    {
      dbSchema: "public",
      dbName: "orders",
      exposedName: "orders",
      isView: false,
      writable: true,
      columns: [
        { dbName: "id", exposedName: "id", dbType: "int4", edmType: "Edm.Int32", nullable: false, isPrimaryKey: true, isAutoGenerated: true, isComputed: false, isFallbackType: false },
        { dbName: "total", exposedName: "total", dbType: "numeric", edmType: "Edm.Decimal", nullable: false, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
        { dbName: "status", exposedName: "status", dbType: "text", edmType: "Edm.String", nullable: true, isPrimaryKey: false, isAutoGenerated: false, isComputed: false, isFallbackType: false },
      ],
      primaryKey: ["id"],
      uniqueConstraints: [],
      foreignKeys: [],
    },
  ],
};

const RUNTIME: ServiceRuntime = {
  name: "sales",
  connectorType: "postgresql",
  connection: { tls: { mode: "disable", allowInvalid: false }, extra: {} },
  schema: SCHEMA,
  options: DEFAULT_SERVICE_OPTIONS,
  schemaVersion: "1",
  status: "active",
};

function makeRow(fields: Record<string, unknown>): Row {
  const r = new Row();
  for (const [k, v] of Object.entries(fields)) r.set(k, v);
  return r;
}

function makeQueryExecutor(rows: Row[] = [], hasMore = false): QueryExecutor {
  return {
    query: vi.fn().mockResolvedValue({ rows, hasMore }),
    count: vi.fn().mockResolvedValue(rows.length),
  };
}

function makeWriteExecutor(affectedCount = 1, rows: Row[] = []): WriteExecutor {
  return {
    write: vi.fn().mockResolvedValue({ affectedCount, records: rows }),
    writeAtomic: vi.fn().mockResolvedValue([]),
  };
}

const visibleServices: VisibleServicesProvider = async () => ["sales"];

function makeConfig(
  queryExec?: QueryExecutor,
  writeExec?: WriteExecutor,
  allowWrites = false,
): McpHandlerConfig {
  return {
    resolveRuntime: async (name) => (name === "sales" ? RUNTIME : undefined),
    getQueryExecutor: () => queryExec ?? makeQueryExecutor(),
    getWriteExecutor: () => writeExec,
    policyEngine: new PolicyEngine(),
    resolveRoleRules: async () => [],
    rowFilterParser: () => { throw new Error("no row filters in test"); },
    visibleServices,
    options: { enabled: true, allowWrites, maxRowsPerCall: 200 },
  };
}

function rpc(method: string, params?: unknown): Record<string, unknown> {
  return { jsonrpc: "2.0", id: 1, method, ...(params !== undefined ? { params } : {}) };
}

describe("McpServer", () => {
  describe("initialize", () => {
    it("returns protocol version and capabilities", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(rpc("initialize"), DEV_BYPASS_IDENTITY);
      expect(resp).not.toBeNull();
      expect((resp!["result"] as Record<string, unknown>)["protocolVersion"]).toBe("2024-11-05");
    });
  });

  describe("notifications/initialized", () => {
    it("returns null (no response for notification)", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(rpc("notifications/initialized"), DEV_BYPASS_IDENTITY);
      expect(resp).toBeNull();
    });
  });

  describe("ping", () => {
    it("returns empty result", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(rpc("ping"), DEV_BYPASS_IDENTITY);
      expect(resp!["result"]).toEqual({});
    });
  });

  describe("unknown method", () => {
    it("returns -32601 error", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(rpc("nonexistent"), DEV_BYPASS_IDENTITY);
      expect((resp!["error"] as Record<string, unknown>)["code"]).toBe(-32601);
    });
  });

  describe("tools/list", () => {
    it("includes base tools and service-specific tools", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(rpc("tools/list"), DEV_BYPASS_IDENTITY);
      const tools = ((resp!["result"] as Record<string, unknown>)["tools"] as unknown[]);
      const names = (tools as Record<string, unknown>[]).map((t) => t["name"]);
      expect(names).toContain("list_services");
      expect(names).toContain("explain_filter_syntax");
      expect(names).toContain("sales_list_tables");
      expect(names).toContain("sales_query");
      expect(names).toContain("sales_count");
    });

    it("includes write tools when allowWrites=true and executor present", async () => {
      const server = new McpServer(makeConfig(undefined, makeWriteExecutor(), true));
      const resp = await server.handle(rpc("tools/list"), DEV_BYPASS_IDENTITY);
      const tools = ((resp!["result"] as Record<string, unknown>)["tools"] as unknown[]);
      const names = (tools as Record<string, unknown>[]).map((t) => t["name"]);
      expect(names).toContain("sales_insert");
      expect(names).toContain("sales_update");
      expect(names).toContain("sales_delete");
    });

    it("excludes write tools when allowWrites=false", async () => {
      const server = new McpServer(makeConfig(undefined, makeWriteExecutor(), false));
      const resp = await server.handle(rpc("tools/list"), DEV_BYPASS_IDENTITY);
      const tools = ((resp!["result"] as Record<string, unknown>)["tools"] as unknown[]);
      const names = (tools as Record<string, unknown>[]).map((t) => t["name"]);
      expect(names).not.toContain("sales_insert");
    });
  });

  describe("tools/call - list_services", () => {
    it("returns visible service names", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "list_services", arguments: {} }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      expect(Array.isArray(structured["services"])).toBe(true);
      expect((structured["services"] as string[])).toContain("sales");
    });
  });

  describe("tools/call - explain_filter_syntax", () => {
    it("returns filter syntax help", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "explain_filter_syntax", arguments: {} }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      expect(typeof structured["syntax"]).toBe("string");
      expect((structured["syntax"] as string).length).toBeGreaterThan(10);
    });
  });

  describe("tools/call - sales_list_tables", () => {
    it("returns table names", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_list_tables", arguments: {} }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      const tables = structured["tables"] as Record<string, unknown>[];
      expect(tables.some((t) => t["name"] === "orders")).toBe(true);
    });
  });

  describe("tools/call - sales_describe_table", () => {
    it("returns column info", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_describe_table", arguments: { table: "orders" } }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      const columns = structured["columns"] as Record<string, unknown>[];
      expect(columns.some((c) => c["name"] === "total")).toBe(true);
    });

    it("returns error for unknown table", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_describe_table", arguments: { table: "nonexistent" } }),
        DEV_BYPASS_IDENTITY,
      );
      const result = resp!["result"] as Record<string, unknown>;
      expect(result["isError"]).toBe(true);
    });
  });

  describe("tools/call - sales_query", () => {
    it("returns rows", async () => {
      const rows = [makeRow({ id: 1, total: 99.9, status: "open" })];
      const server = new McpServer(makeConfig(makeQueryExecutor(rows)));
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_query", arguments: { table: "orders" } }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      expect(structured["rowCount"]).toBe(1);
      expect(Array.isArray(structured["rows"])).toBe(true);
    });

    it("applies filter argument", async () => {
      const exec = makeQueryExecutor([]);
      const server = new McpServer(makeConfig(exec));
      await server.handle(
        rpc("tools/call", { name: "sales_query", arguments: { table: "orders", filter: "total > 100" } }),
        DEV_BYPASS_IDENTITY,
      );
      const queryCall = (exec.query as ReturnType<typeof vi.fn>).mock.calls[0]![0];
      expect(queryCall.query.filter).toBeDefined();
    });
  });

  describe("tools/call - sales_count", () => {
    it("returns row count", async () => {
      const exec = makeQueryExecutor([]);
      (exec.count as ReturnType<typeof vi.fn>).mockResolvedValue(42);
      const server = new McpServer(makeConfig(exec));
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_count", arguments: { table: "orders" } }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      expect(structured["count"]).toBe(42);
    });
  });

  describe("tools/call - sales_insert (write=true)", () => {
    it("inserts and returns result", async () => {
      const rows = [makeRow({ id: 99, total: 10, status: "open" })];
      const writeExec = makeWriteExecutor(1, rows);
      const server = new McpServer(makeConfig(undefined, writeExec, true));
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_insert", arguments: { table: "orders", record: { total: 10, status: "open" } } }),
        DEV_BYPASS_IDENTITY,
      );
      const structured = (resp!["result"] as Record<string, unknown>)["structuredContent"] as Record<string, unknown>;
      expect(structured["inserted"]).toBe(1);
    });

    it("returns error when writes disabled", async () => {
      const server = new McpServer(makeConfig(undefined, makeWriteExecutor(), false));
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_insert", arguments: { table: "orders", record: { total: 10 } } }),
        DEV_BYPASS_IDENTITY,
      );
      const result = resp!["result"] as Record<string, unknown>;
      expect(result["isError"]).toBe(true);
    });
  });

  describe("tools/call - sales_delete safety gate", () => {
    it("requires confirm:true", async () => {
      const server = new McpServer(makeConfig(undefined, makeWriteExecutor(), true));
      const resp = await server.handle(
        rpc("tools/call", { name: "sales_delete", arguments: { table: "orders", key: { id: 1 } } }),
        DEV_BYPASS_IDENTITY,
      );
      const result = resp!["result"] as Record<string, unknown>;
      expect(result["isError"]).toBe(true);
      expect(((result["content"] as unknown[])[0] as Record<string, unknown>)["text"]).toContain("confirm");
    });
  });

  describe("tools/call - unknown tool", () => {
    it("returns isError:true", async () => {
      const server = new McpServer(makeConfig());
      const resp = await server.handle(
        rpc("tools/call", { name: "nonexistent_tool", arguments: {} }),
        DEV_BYPASS_IDENTITY,
      );
      const result = resp!["result"] as Record<string, unknown>;
      expect(result["isError"]).toBe(true);
    });
  });
});
