import type { QueryRequest } from "../../src/core/query.js";
import type { ColumnModel, ForeignKeyModel, SchemaSnapshot, TableModel } from "../../src/core/schema.js";

export function col(name: string, edmType: string, opts: Partial<ColumnModel> = {}): ColumnModel {
  return {
    dbName: name,
    exposedName: name,
    dbType: "x",
    edmType,
    nullable: opts.nullable ?? true,
    isPrimaryKey: opts.isPrimaryKey ?? false,
    isAutoGenerated: opts.isAutoGenerated ?? false,
    isComputed: opts.isComputed ?? false,
    isFallbackType: opts.isFallbackType ?? false,
    ...opts,
  };
}

export function table(opts: {
  dbName: string;
  columns: ColumnModel[];
  dbSchema?: string;
  exposedName?: string;
  primaryKey?: string[];
  foreignKeys?: ForeignKeyModel[];
  isView?: boolean;
  writable?: boolean;
}): TableModel {
  return {
    dbSchema: opts.dbSchema ?? "",
    dbName: opts.dbName,
    exposedName: opts.exposedName ?? opts.dbName,
    isView: opts.isView ?? false,
    writable: opts.writable ?? true,
    columns: opts.columns,
    primaryKey: opts.primaryKey ?? [],
    uniqueConstraints: [],
    foreignKeys: opts.foreignKeys ?? [],
  };
}

export function snapshot(engine: string, tables: TableModel[]): SchemaSnapshot {
  return { version: 1, engine, collectedAt: new Date(0).toISOString(), tables };
}

export function query(serviceName: string, t: string, overrides: Partial<QueryRequest> = {}): QueryRequest {
  return { serviceName, table: t, orderBy: [], expand: [], count: false, ...overrides };
}
